### ISSUE TITLE
[help needed] very slow startup outside of git managed folders

### ISSUE THREAD

**Issue by evoludigit** [LunarVim/LunarVim#1259]
### Problem description
[edit: found the reason and changed title accordingly, could be seen as a feature ?]

Hello,

thanks Christian for your dedication on this awesome project.

I am running out of ideas here so I am posting this hoping someone else has encountered the problem or will benefit from this.

I have very slow startup (8 ~ 10) seconds) from lunarvim if I run it from outside the directory of my current project. [edit: from any git managed directory].
- Terminal is frozen
- No display of the cursor from the start up menu

Everything works as expected (ie blazing fast) with
- nvim vanilla
- nvim with all of my init.vim configuration
- lunarvim launched from my main project directory root
- lunarvim launched from this project subfolders

lunarvim loads painfully slow everywhere else [edit: in any non git managed directory], with or without my main project Python Poetry virtual environment activated. 
the command :scriptnames does not list anything custom from what I can see.

What I have done to fix the problem:
- clean reinstall lunarvim as stated in the docs, both with the `--overwrite` argument and by removing the directories listed in the documentation

```
rm -rf ~/.local/share/lunarvim
sudo rm /usr/local/bin/lvim
rm -rf ~/.local/share/applications/lvim.desktop
```

- reinstall nvim and disabled my custom nvim config by moving it to .config/my_nvim_config

### LunarVim version

LunarVim 0.5.1 (master)

### Neovim version (>= 0.5)

NVIM v0.5.0

### Relevant log output

```shell
-------------------------------------------------------------
--startup time does not show the painfully slow frozen screen
-------------------------------------------------------------

times in msec
 clock   self+sourced   self:  sourced script
 clock   elapsed:              other lines

000.006  000.006: --- NVIM STARTING ---
000.225  000.219: locale set
000.489  000.264: inits 1
000.501  000.012: window checked
000.503  000.002: parsing arguments
000.532  000.029: expanding arguments
000.562  000.030: inits 2
000.839  000.277: init highlight
000.840  000.001: waiting for UI
001.567  000.727: done waiting for UI
001.587  000.020: initialized screen early for UI
001.649  000.061: --cmd commands
028.072  000.180  000.180: sourcing /usr/share/nvim/runtime/syntax/syncolor.vim
030.552  003.557  003.377: sourcing /home/me/.local/share/lunarvim/lvim/colors/spacegray.vim
038.314  036.651  033.093: sourcing /home/me/.local/share/lunarvim/lvim/init.lua
038.321  000.022: sourcing vimrc file(s)
042.411  000.012  000.012: sourcing /home/me/.local/share/lunarvim/site/pack/packer/start/nvim-treesitter/ftdetect/gdscript.vim
042.435  000.008  000.008: sourcing /home/me/.local/share/lunarvim/site/pack/packer/start/nvim-treesitter/ftdetect/gomod.vim
042.464  000.019  000.019: sourcing /home/me/.local/share/lunarvim/site/pack/packer/start/nvim-treesitter/ftdetect/query.vim
042.629  000.029  000.029: sourcing /home/me/.local/share/lunarvim/lvim/ftdetect/fish.lua
042.656  000.016  000.016: sourcing /home/me/.local/share/lunarvim/lvim/ftdetect/julia.lua
042.683  000.015  000.015: sourcing /home/me/.local/share/lunarvim/lvim/ftdetect/plaintex.lua
042.712  000.019  000.019: sourcing /home/me/.local/share/lunarvim/lvim/ftdetect/zig.lua
042.902  004.551  004.434: sourcing /usr/share/nvim/runtime/filetype.vim
043.073  000.024  000.024: sourcing /usr/share/nvim/runtime/ftplugin.vim
043.237  000.021  000.021: sourcing /usr/share/nvim/runtime/indent.vim
043.466  000.011  000.011: sourcing /home/me/.local/share/lunarvim/lvim/colors/spacegray.vim
043.902  000.495  000.484: sourcing /usr/share/nvim/runtime/syntax/synload.vim
043.955  000.581  000.086: sourcing /usr/share/nvim/runtime/syntax/syntax.vim
044.733  000.274  000.274: sourcing /usr/share/nvim/runtime/plugin/gzip.vim
044.755  000.008  000.008: sourcing /usr/share/nvim/runtime/plugin/health.vim
044.911  000.145  000.145: sourcing /usr/share/nvim/runtime/plugin/man.vim
045.266  000.137  000.137: sourcing /usr/share/nvim/runtime/pack/dist/opt/matchit/plugin/matchit.vim
045.338  000.413  000.276: sourcing /usr/share/nvim/runtime/plugin/matchit.vim
045.448  000.098  000.098: sourcing /usr/share/nvim/runtime/plugin/matchparen.vim
045.817  000.356  000.356: sourcing /usr/share/nvim/runtime/plugin/netrwPlugin.vim
045.949  000.008  000.008: sourcing /home/me/.local/share/nvim/rplugin.vim
045.954  000.112  000.104: sourcing /usr/share/nvim/runtime/plugin/rplugin.vim
046.049  000.081  000.081: sourcing /usr/share/nvim/runtime/plugin/shada.vim
046.087  000.018  000.018: sourcing /usr/share/nvim/runtime/plugin/spellfile.vim
046.222  000.110  000.110: sourcing /usr/share/nvim/runtime/plugin/tarPlugin.vim
046.300  000.058  000.058: sourcing /usr/share/nvim/runtime/plugin/tohtml.vim
046.330  000.013  000.013: sourcing /usr/share/nvim/runtime/plugin/tutor.vim
046.475  000.129  000.129: sourcing /usr/share/nvim/runtime/plugin/zipPlugin.vim
049.061  002.368  002.368: sourcing /home/me/.config/lvim/plugin/packer_compiled.lua
049.068  001.386: loading plugins
050.005  000.772  000.772: sourcing /home/me/.local/share/lunarvim/site/pack/packer/start/astronauta.nvim/plugin/astronauta.vim
050.138  000.045  000.045: sourcing /home/me/.local/share/lunarvim/site/pack/packer/start/nlsp-settings.nvim/plugin/nlspsetting.vim
050.321  000.077  000.077: sourcing /home/me/.local/share/lunarvim/site/pack/packer/start/nvim-lspconfig/plugin/lspconfig.vim
050.499  000.087  000.087: sourcing /home/me/.local/share/lunarvim/site/pack/packer/start/nvim-tree.lua/plugin/tree.vim
051.239  000.650  000.650: sourcing /home/me/.local/share/lunarvim/site/pack/packer/start/nvim-treesitter/plugin/nvim-treesitter.vim
051.340  000.010  000.010: sourcing /home/me/.local/share/lunarvim/site/pack/packer/start/nvim-treesitter/ftdetect/gdscript.vim
051.387  000.009  000.009: sourcing /home/me/.local/share/lunarvim/site/pack/packer/start/nvim-treesitter/ftdetect/gomod.vim
051.420  000.016  000.016: sourcing /home/me/.local/share/lunarvim/site/pack/packer/start/nvim-treesitter/ftdetect/query.vim
051.514  000.031  000.031: sourcing /home/me/.local/share/lunarvim/site/pack/packer/start/nvim-web-devicons/plugin/nvim-web-devicons.vim
051.657  000.033  000.033: sourcing /home/me/.local/share/lunarvim/site/pack/packer/start/plenary.nvim/plugin/plenary.vim
052.008  000.243  000.243: sourcing /home/me/.local/share/lunarvim/site/pack/packer/start/telescope.nvim/plugin/telescope.vim
052.436  000.338  000.338: sourcing /home/me/.local/share/lunarvim/site/pack/packer/start/vim-rooter/plugin/rooter.vim
052.546  001.167: loading packages
052.667  000.121: loading after plugins
052.678  000.011: inits 3
053.403  000.724: reading ShaDa
054.066  000.017  000.017: sourcing /home/me/.local/share/lunarvim/site/pack/packer/opt/which-key.nvim/plugin/which-key.vim
055.670  000.427  000.427: sourcing /home/me/.local/share/lunarvim/site/pack/packer/opt/dashboard-nvim/plugin/dashboard.vim
056.062  000.029  000.029: sourcing /home/me/.local/share/lunarvim/site/pack/packer/opt/nvim-toggleterm.lua/plugin/toggleterm.vim
057.930  000.041  000.041: sourcing /home/me/.local/share/lunarvim/site/pack/packer/opt/barbar.nvim/autoload/bufferline/highlight.vim
059.609  002.361  002.320: sourcing /home/me/.local/share/lunarvim/site/pack/packer/opt/barbar.nvim/plugin/bufferline.vim
060.106  000.319  000.319: sourcing /home/me/.local/share/lunarvim/site/pack/packer/opt/galaxyline.nvim/plugin/galaxyline.vim
060.604  000.085  000.085: sourcing /home/me/.local/share/lunarvim/site/pack/packer/opt/dashboard-nvim/autoload/dashboard.vim
060.856  004.214: opening buffers
068.029  007.174: BufEnter autocommands
068.032  000.003: editing files in windows
068.231  000.035  000.035: sourcing /home/me/.local/share/lunarvim/site/pack/packer/opt/nvim-lspinstall/plugin/lspinstall.vim
077.360  000.018  000.018: sourcing /home/me/.local/share/lunarvim/site/pack/packer/opt/dashboard-nvim/autoload/dashboard/utils.vim
077.604  000.067  000.067: sourcing /home/me/.local/share/lunarvim/site/pack/packer/opt/dashboard-nvim/autoload/dashboard/section.vim
078.350  000.134  000.134: sourcing /usr/share/nvim/runtime/autoload/provider/clipboard.vim
081.054  000.085  000.085: sourcing /home/me/.local/share/lunarvim/site/pack/packer/opt/dashboard-nvim/syntax/dashboard.vim
083.590  015.219: VimEnter autocommands
083.595  000.005: UIEnter autocommands
083.599  000.004: before starting main loop
085.040  001.442: first screen update
085.044  000.004: --- NVIM STARTED ---
```

### Screenshots

![lunarvim](https://user-images.githubusercontent.com/36459148/128626087-519cff85-670d-4c65-9d9f-086a558b692b.png)
this is what I get for +10 seconds

expected result:
![expected](https://user-images.githubusercontent.com/36459148/128626192-c1bec7ff-6479-4c32-ad90-eaaec6e6260b.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by evoludigit** [comment]
OK, found the problem. It occurs only outside of git managed repositories. I do not know if it's a bug or a feature but it totally makes sense now.

**Comment by rebuilt** [comment]
Can you try running with an empty config file please?   Do you have nerd fonts installed?  Can you try disabling the dashboard custom header?  I'm not at a computer but it should be something like lvim.builltin.dashboard.custom_header = "".  Can you post any relevant errors from the logs in .cache/nvim.

**Comment by evoludigit** [comment]
@rebuilt is this behavior expected outside a git managed repo ?

- [x] empty config file: same problem
- [x] nerdfonts is installed.
- [x] lvim.builltin.dashboard.custom_header = "" is indeed the correct syntax. Same 10 seconds delay.
- [x] nothing relevant in the .cache/nvim

**Comment by PasiBergman** [comment]
Can you please try the following.
1. test if disabling `vim-rooter` changes the behaviour. Disable with `lvim.builtin.rooter.active = false` in your `~/.config/lvim/config.lua` and then issue `:PackerCompile` in LunarVim
2. test if removing LSP clients, formatters and linters changes the behaviour. LSP clients are disabled by e.g. uninstalling the language servers, each with `:LspUninstall <ls>`. Formatters and linters are disabled by not specifying them in your config (e.g. in `~/.config/lvim/config.lua`
3. Open another terminal and issue the following commands:
```sh
LVIMLOG=$HOME/lvim.log
touch $LVIMLOG
tail -f $LVIMLOG
```
While tail starts to wait for logs startup LunarVim on another terminal window with the following commands:
```sh
LVIMLOG=$HOME/lvim.log
lvim -V9$LVIMLOG
```
In the `tail` terminal window's log, try to catch the point where the system halts.

**Comment by rebuilt** [comment]
Are these python files you're opening up?  We've had a problem with pyright and the fact that the behavior is different inside vs outside a git managed repo leads me to believe it has something to do with the LSP detecting the root folder.  Any language server depends of finding the root folder for proper functioning.   It needs to scan your entire directory to understand how to work with your project.  Can you uninstall the language server you're using to see if that makes any difference?

**Comment by ahmedkhalf** [comment]
> Can you please try the following.
> 
>     1. test if disabling `vim-rooter` changes the behaviour. Disable with `lvim.builtin.rooter.active = false` in your `~/.config/lvim/config.lua` and then issue `:PackerCompile` in LunarVim

Sry for the shameless plug but I just wanna say that I'm making a plugin like vim-rooter, but it uses multi-threading + async using Neovim's built-in libuv lua library. So if this issue happens to stem from vim-rooter, my plugin could help remedy the situation as it carries virtually no slowdown to the main neovim UI thread.

That being said project.nvim is not complete and cd'ing to the root dir is not its only scope, I have other goals like telescope integration and session management.

**Comment by evoludigit** [comment]
@PasiBergman thanks for the tips

1. as @ahmedkhalf  guessed, I had an error parsing the config file with the `lvim.builtin.rooter.active = false` instruction
2. upon reinstalling, I did not install any Lsp and basically have an empty config.lua file, except for the disabled custom header suggested by @rebuilt
3. the tail immediately issues the following lines, even before I launch lvim in the first terminal:
```
[me@arch ~]$ export LVIMLOG=$HOME/lvim.log 
[me@arch ~]$ tail -f $LVIMLOG 
069.847  000.035  000.035: sourcing /home/me/.local/share/lunarvim/site/pack/packer/opt/nvim-lspinstall/plugin/lspinstall.vim 
078.994  000.018  000.018: sourcing /home/me/.local/share/lunarvim/site/pack/packer/opt/dashboard-nvim/autoload/dashboard/utils.vim 
079.236  000.066  000.066: sourcing /home/me/.local/share/lunarvim/site/pack/packer/opt/dashboard-nvim/autoload/dashboard/section.vim 
079.661  000.132  000.132: sourcing /usr/share/nvim/runtime/autoload/provider/clipboard.vim 
082.246  000.060  000.060: sourcing /home/me/.local/share/lunarvim/site/pack/packer/opt/dashboard-nvim/syntax/dashboard.vim 
084.510  014.554: VimEnter autocommands 
084.513  000.003: UIEnter autocommands 
084.515  000.002: before starting main loop 
085.927  001.412: first screen update 
085.929  000.002: --- NVIM STARTED --- 
```

Launching LunarVim does not issue any additionnal lines, the screen is frozen for ~10 secs then I can access the tree.

@rebuilt I do not open any specific file, I launch lvim on an empty buffer.

**Comment by PasiBergman** [comment]
1. Ok
2. Even if you have installed language servers, manually or with `:LspInstall <languageserver>` they do not show in `config.lua`.
3. Most likely, because you already had an existing `$HOME/lvim.log` file, and tail is showing the last lines of the existing file. You should launch lvim int the first terminal, to get verbose logs from neovim/LunarVim.

**Comment by evoludigit** [comment]
thank you very much for your quick feedback.
2. `LspUninstall python `& `LspUninstall lua`  show no lsp are installed (`Language server is not installed`)
3. it works indeed, sorry my fault.

Here are the culprits:
```
Executing command: "'/bin/zsh' '-c' 'git -C '/home/me' rev-parse --show-toplevel'"
Executing command: "'/bin/zsh' '-c' 'git -C '/home/me' config --type=bool status.showUntrackedFiles'"
Executing command: "'/bin/zsh' '-c' 'git -C '/home/me' status --porcelain=v1 --ignored=matching -u'"
```

**Comment by abzcoding** [comment]
> thank you very much for your quick feedback.
> 2. `LspUninstall python `& `LspUninstall lua` show no lsp are installed (`Language server is not installed`)
> 3. it works indeed, sorry my fault.
> 
> Here are the culprits:
> 
> ```
> Executing command: "'/bin/zsh' '-c' 'git -C '/home/me' rev-parse --show-toplevel'"
> Executing command: "'/bin/zsh' '-c' 'git -C '/home/me' config --type=bool status.showUntrackedFiles'"
> Executing command: "'/bin/zsh' '-c' 'git -C '/home/me' status --porcelain=v1 --ignored=matching -u'"
> ```

so is the issue fixed now or?

**Comment by evoludigit** [comment]
@abzcoding, thanks for asking for clarification, I realize I could have worded my message better. @PasiBergman instructions enabled to show the logs where the freeze happen on startup.

I do not know why these commands are executed however upon lauching LunarVim, so the issue is not fixed.

**Comment by PasiBergman** [comment]
@evoludigit 
Those git command seem to be initialized from the `nvim-tree.lua` plugin. 
https://github.com/kyazdani42/nvim-tree.lua/blob/6175d63eaecdc7d80105825f89a6c9864c4dd432/lua/nvim-tree/git.lua#L16

**Comment by ahmedkhalf** [comment]
> Here are the culprits:
> 
> Executing command: "'/bin/zsh' '-c' 'git -C '/home/me' rev-parse --show-toplevel'"

This comes from `nvim-tree.git`, `create_root` function, line 70

> Executing command: "'/bin/zsh' '-c' 'git -C '/home/me' config --type=bool status.showUntrackedFiles'"

This comes from `nvim-tree.git`,  `update_root_status` function, line 16

> Executing command: "'/bin/zsh' '-c' 'git -C '/home/me' status --porcelain=v1 --ignored=matching -u'"

This comes from `nvim-tree.git`,  `update_root_status` function, line 21

I doubt it comes from nvim-tree though, on my system it's very fast, and 10 seconds is pretty darn slow.

---

What os do you use?
Also could you please update to the rolling branch and see if using `lvim.builtin.rooter.active = false` fixes it?
Also finally run `PackerSync`, and `PackerCompile`

@evoludigit

**Comment by PasiBergman** [comment]
@evoludigit 
If this is a typical and real scenario for your use, I suggest you add the following lines to LunarVim config, e.g. to `~/.config/lvim/config.lua` or `~/.config/lvim/lv-config.lua` depending on which config file your setup uses.
```lua
lvim.builtin.nvimtree.show_icons.git = 0
vim.cmd [[vim.g.nvim_tree_git_hl = 0]]
```

**Comment by evoludigit** [comment]
thank you very much @PasiBergman and @ahmedkhalf 

I am running Archlinux box.

There was in fact a `~/.git` folder in my home directory that had been created by Luke Smith's LARBS installation script.

Deleting this folder solved the problem, both when loading a test file from home or any other non git managed repository.
