### ISSUE TITLE
[Feature]: Use Packer to load core plugins, not download/install

### ISSUE THREAD

**Issue by chase** [LunarVim/LunarVim#2052]
### Feature motivation

[It's been addressed before](https://github.com/LunarVim/LunarVim/issues/1399), but our core code updates with Packer and often becomes incredibly fragile, displaying errors that make LunarVim appear to be entirely broken and makes unwilling to continue.

Also, Packer on LvimUpdate with the new setup took around 63 seconds for me on a 200 Mbps connection.
This seems to be because the downloads themselves are now done in serial instead of parallel. This could be fixed directly, but we can optimize things things a little better on our end without having to worry about Packer messing up.

The current method of handling the initial install is still fragile because Packer still handles it as a remote git repository.

### Describe the expected solution

Assumptions:

1. Core plugins are pinned to a SHA
2. Core plugins reside on GitHub
3. The host system has `curl` and `unzip` (even Git for Windows has these)

We can entirely avoid the mess caused by Packer trying to manage a git repository and cloning unnecessary objects by just download the commit's zipped snapshot and referencing it as an absolute path.

Let's use `nvim-telescope/telescope.nvim` pinned at commit `27294d73e4562cbc83c9c488b4618f012deade7e` as an example:

- Check if `telescope.nvim-27294d73e4562cbc83c9c488b4618f012deade7e` exists in a central location `/.local/share/lunarvim/core_plugins`, if not then continue
- Download: `curl -LO https://github.com/nvim-telescope/telescope.nvim/archive/27294d73e4562cbc83c9c488b4618f012deade7e.zip`
- Unzip: `unzip 27294d73e4562cbc83c9c488b4618f012deade7e.zip`
- Relocate to the central location: `mv telescope.nvim-27294d73e4562cbc83c9c488b4618f012deade7e ~/.local/share/lunarvim/core_plugins/`
- In our plugin loader, only for these core plugins, rewrite the path to be the absolute path like this:
```
  {
    "/home/chase/.local/share/lunarvim/core_plugins/telescope.nvim-27294d73e4562cbc83c9c488b4618f012deade7e",
    commit = commit.telescope,
    config = function()
      require("lvim.core.telescope").setup()
    end,
    disable = not lvim.builtin.telescope.active,
  },
```

---

Installation and updates should _not_ use the usual `init.lua` because it loads the plugins and should _not_ be run directly as a Vim command in a running instance, this leads to the errors we see. **Why?** A lot of it is caused by use-before-load or having an old version loaded of a plugin loaded with a configuration expecting the updated version.

Updates should instead be run from the command line with a mostly clean state, which we could add as an option in the shim executable we have installed as `lvim`:
`nvim -u install_update.lua --noplugin -n -i NONE --headless`

An unfinished, minimalist example for `install_update.lua` init file:
```
local init_path = debug.getinfo(1, "S").source:sub(2)
local base_dir = init_path:match("(.*[/\\])"):sub(1, -2)

if not vim.tbl_contains(vim.opt.rtp:get(), base_dir) then
  vim.opt.rtp:append(base_dir)
end

require("lvim.bootstrap"):init(base_dir)

local plugins = require "lvim.plugins"

-- TODO: download plugins and unzip using vim.loop.spawn in parallel, using a counter when the last unzip finishes, finish the steps above
```

**Comment by kylo252** [comment]
You probably didn't see the API, but I can actually specify which plugins to update. We can do the check and only request for those that have a mis-matched SHA. 

Here are the results from the SHA generator, which _I haven't really done anything to optimize_:

```console
❯ hyperfine --runs 5 'make generate_plugins_sha' --prepare 'rm latest-sha.lua'
Benchmark 1: make generate_plugins_sha
  Time (mean ± σ):     15.554 s ±  0.635 s    [User: 0.432 s, System: 0.086 s]
  Range (min … max):   14.447 s … 15.993 s    5 runs
  ```

**Comment by chase** [comment]
> You probably didn't see the API, but I can actually specify which plugins to update.

Which API are you talking about? Packer's or one you wrote for LunarVim? Mind giving me a link?

> We can do the check and only request for those that have a mis-matched SHA.

Yes, that's the first step that I wrote:
`Check if telescope.nvim-27294d73e4562cbc83c9c488b4618f012deade7e exists in a central location /.local/share/lunarvim/core_plugins, if not then continue`

> Here are the results from the SHA generator, which _I haven't really done anything to optimize_:
> 
> ```
> ❯ hyperfine --runs 5 'make generate_plugins_sha' --prepare 'rm latest-sha.lua'
> Benchmark 1: make generate_plugins_sha
>   Time (mean ± σ):     15.554 s ±  0.635 s    [User: 0.432 s, System: 0.086 s]
>   Range (min … max):   14.447 s … 15.993 s    5 runs
> ```

I was aware of the SHA generator, which is why I wrote this issue up, it makes rolling out updates and rolling _back_ much easier this way. The SHA is fixed to our plugins list, like a dependency lock file.

**Comment by kylo252** [comment]
> Which API are you talking about? Packer's or one you wrote for LunarVim? Mind giving me a link?

Basically the SHA generator

> I was aware of the SHA generator, which is why I wrote this issue up, it makes rolling out updates and rolling _back_ much easier this way. The SHA is fixed to our plugins list, like a dependency lock file.

I had originally wanted to skip Packer altogether and pull the updates manually and then call `PackerCompile`. However, that didn't quite work out because of the `run` hook, which seems annoying to handle.

---

I noticed that Packer is doing an expensive `fetch` command when a commit is specified
https://github.com/wbthomason/packer.nvim/blob/851c62c5ecd3b5adc91665feda8f977e104162a5/lua/packer/plugin_types/git.lua#L142
I changed that in #2054, and it seems to be much faster now, but it requires some more testing in case I'm missing something obvious.

**Comment by kylo252** [comment]
oops, I guess github doesn't understand the word "partially" 😄

**Comment by chase** [comment]
Although some of the behavior would be beneficial, namely avoiding conflicts caused by user configuration during an update, Packer snapshots are integrated in core and the git fetch is optimized quite well now.

**Comment by kylo252** [comment]
> Packer snapshots are integrated in core

it's more of a manual process, since the snapshot updates the plugins serially...  :disappointed: 

> git fetch is optimized quite well now.

it's still not quite there unfortunately, mainly because of the limit on the number of jobs

> Although some of the behavior would be beneficial

my future plan is to make use of [mason](https://github.com/williamboman/mason.nvim) for this purpose, we'll see if I ever get to that :)
