### ISSUE TITLE
Weird nvim tree bugs when opening/closing files

### ISSUE THREAD

**Issue by sagikazarmark** [LunarVim/LunarVim#2312]
### Problem description

Unfortunately I couldn't find a better way to report this/these bugs. Basically, nvim tree acts weird when opening/closing files:

- When opening vim for the first time and opening nvim tree right after, the cursor cannot be moved (see the video below)
- When closing a file (eg. with ZQ) nvim tree becomes "fullscreen". When I close nvim tree, the closed file is opened again. (see the video below)

I have no idea if this is a lunarvim or nvim tree issue or something else, but it was working fine up until a couple weeks ago.

Happy to provide any details I can, but I'm clueless where to look for the cause of the problem.

### LunarVim version

ffcfdf43062dd4a3a72eda4a657448354ec55262

### Neovim version (>= 0.6.1)

NVIM v0.6.1 Build type: Release LuaJIT 2.1.0-beta3 Compiled by _nixbld4  Features: +acl +iconv +tui

### Operating system/version

macOS 12.2

### Relevant log output

```shell
go: require("go.health").check()
========================================================================
## Binaries
  - INFO: go installed.
  - INFO: Tool installed: dlv
  - INFO: Tool installed: gorename
  - WARNING: Missing tool: richgo
  - INFO: Tool installed: gomodifytags
  - WARNING: Missing tool: ginkgo
  - INFO: Tool installed: gofumpt
  - INFO: Tool installed: gotests
  - INFO: Tool installed: fillstruct
  - INFO: Tool installed: gopls
  - INFO: Tool installed: impl
  - INFO: Tool installed: iferr
  - WARNING: Missing tool: golines
  - WARNING: Missing tool: fixplurals
  - INFO: Tool installed: golangci-lint
  - WARNING: Missing tool: fillswitch
  - INFO: Tool installed: goimports
  - OK: All binaries installed

## Go Plugin Check
  - OK: lspconfig: plugin is installed
  - OK: nvim-treesitter: plugin is installed
  - WARNING: guihua: not installed/loaded
  - WARNING: nvim-dap-virtual-text: not installed/loaded
  - OK: telescope: plugin is installed
  - OK: nvim-treesitter-go is installed
  - OK: nvim-dap: plugin is installed
  - WARNING: nvim-dap-ui: not installed/loaded
  - WARNING: Not all plugin installed

null-ls: require("null-ls.health").check()
========================================================================
  - INFO: no sources registered

nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.6.0
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - WARNING: **julia**: not available
  - OK: **python3**: `Python 3.8.12`
  - OK: **bash**: `GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21)`
  - OK: **tar**: `bsdtar 3.5.1 - libarchive 3.5.1 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8 `
  - OK: **gzip**: `Apple gzip 352.40.6`
  - OK: **curl**: `curl 7.77.0 (x86_64-apple-darwin21.0) libcurl/7.77.0 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.42.0`
  - OK: **Go**: `go version go1.17 darwin/amd64`
  - OK: **sh**: `Ok`
  - OK: **node**: `v16.13.2`
  - OK: **Ruby**: `ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]`
  - OK: **wget**: `GNU Wget 1.21.2, összeállítva darwin17.7.0 rendszeren.`
  - OK: **python3_host_prog**: `Python 3.9.9`
  - OK: **java**: `Ok`
  - OK: **RubyGem**: `3.0.3.1`
  - OK: **javac**: `javac 17.0.2`
  - OK: **pip3**: `pip 21.2.4 from /usr/local/lib/python3.8/site-packages/pip (python 3.8)`
  - OK: **npm**: `8.1.2`

nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.4 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.13.2 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 13.0.0 (clang-1300.0.29.30)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - css            ✓ . ✓ ✓ ✓ 
  - toml           ✓ ✓ ✓ ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - hcl            ✓ . ✓ ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - vim            ✓ ✓ . . ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - graphql        ✓ . . ✓ ✓ 
  - gomod          ✓ . . . ✓ 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - dockerfile     ✓ . . . ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - php            ✓ ✓ ✓ ✓ ✓ 
  - nix            ✓ ✓ ✓ . ✓ 
  - yaml           ✓ ✓ ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: Disabled (g:loaded_python_provider=0).

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/nix/store/aaqqajp6dag80q0jqlqpzbc08gli4zvp-neovim-0.6.1/bin/nvim-python3"
  - INFO: Executable: /nix/store/aaqqajp6dag80q0jqlqpzbc08gli4zvp-neovim-0.6.1/bin/nvim-python3
  - INFO: Python version: 3.9.9
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]
  - INFO: Host: /nix/store/aaqqajp6dag80q0jqlqpzbc08gli4zvp-neovim-0.6.1/bin/nvim-ruby
  - WARNING: Gem "neovim" is out-of-date. Installed: 0.8.1, latest: 0.9.0
    - ADVICE:
      - Run in shell: gem update neovim

## Node.js provider (optional)
  - INFO: Disabled (g:loaded_node_provider=0).

## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed

telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.2

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided

## Telescope Extension: `projects`
  - INFO: No healthcheck provided

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: /Users/marksk/.cache/nvim/lsp.log
  - INFO: Log size: 42038 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 14
  - OK: Loaded parser for bash: ABI version 13
  - OK: Loaded parser for css: ABI version 13
  - OK: Loaded parser for dockerfile: ABI version 13
  - OK: Loaded parser for go: ABI version 13
  - OK: Loaded parser for gomod: ABI version 13
  - OK: Loaded parser for graphql: ABI version 13
  - OK: Loaded parser for hcl: ABI version 13
  - OK: Loaded parser for javascript: ABI version 13
  - OK: Loaded parser for json: ABI version 13
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for nix: ABI version 13
  - OK: Loaded parser for php: ABI version 13
  - OK: Loaded parser for rust: ABI version 13
  - OK: Loaded parser for toml: ABI version 13
  - OK: Loaded parser for typescript: ABI version 13
  - OK: Loaded parser for vim: ABI version 13
  - OK: Loaded parser for yaml: ABI version 13

which_key: health#which_key#check
========================================================================
## WhichKey: checking conflicting keymaps
  - WARNING: conflicting keymap exists for mode **"i"**, lhs: **"<C-S>d"**
  - INFO: rhs: `""<Left>`
  - WARNING: conflicting keymap exists for mode **"i"**, lhs: **"<C-S>s"**
  - INFO: rhs: `[]<Left>`
  - WARNING: conflicting keymap exists for mode **"i"**, lhs: **"<C-S>["**
  - INFO: rhs: `[]<Left>`
  - WARNING: conflicting keymap exists for mode **"i"**, lhs: **"<C-S>a"**
  - INFO: rhs: `<lt>><Left>`
  - WARNING: conflicting keymap exists for mode **"i"**, lhs: **"<C-S>>"**
  - INFO: rhs: `<lt>><Left>`
  - WARNING: conflicting keymap exists for mode **"i"**, lhs: **"<C-S><lt>"**
  - INFO: rhs: `<lt>><Left>`
  - WARNING: conflicting keymap exists for mode **"i"**, lhs: **"<C-S>t"**
  - INFO: rhs: <Left>`
  - WARNING: conflicting keymap exists for mode **"i"**, lhs: **"<C-S>{"**
  - INFO: rhs: `{}<Left>`
  - WARNING: conflicting keymap exists for mode **"i"**, lhs: **"<C-S>q"**
  - INFO: rhs: `''<Left>`
  - WARNING: conflicting keymap exists for mode **"i"**, lhs: **"<C-S>)"**
  - INFO: rhs: `()<Left>`
  - WARNING: conflicting keymap exists for mode **"i"**, lhs: **"<C-S>b"**
  - INFO: rhs: `()<Left>`
  - WARNING: conflicting keymap exists for mode **"i"**, lhs: **"<C-S>}"**
  - INFO: rhs: `{}<Left>`
  - WARNING: conflicting keymap exists for mode **"i"**, lhs: **"<C-S>'"**
  - INFO: rhs: `''<Left>`
  - WARNING: conflicting keymap exists for mode **"i"**, lhs: **"<C-S>("**
  - INFO: rhs: `()<Left>`
  - WARNING: conflicting keymap exists for mode **"i"**, lhs: **"<C-S>]"**
  - INFO: rhs: `[]<Left>`
  - WARNING: conflicting keymap exists for mode **"i"**, lhs: **"<C-S>\""**
  - INFO: rhs: `""<Left>`
  - WARNING: conflicting keymap exists for mode **"i"**, lhs: **"<C-S>`"**
  - INFO: rhs: ```<Left>`
  - WARNING: conflicting keymap exists for mode **"i"**, lhs: **"<C-S>B"**
  - INFO: rhs: `{}<Left>`

18:25:43 [DEBUG] lvim: { "269a35d" }                  file="lua/lvim/utils/git.lua", line=31
18:41:45 [DEBUG] lvim: "Activated mac keymappings"    file="lvim/lua/lvim/keymappings.lua", line=116
18:41:45 [DEBUG] lvim: "loading plugins configuration" file="lvim/lua/lvim/plugin-loader.lua", line=77
18:41:45 [DEBUG] lvim: "Starting LunarVim"            file="share/lunarvim/lvim/init.lua", line=16
18:41:45 [DEBUG] lvim: "Setting up LSP support"       file="lua/lvim/lsp/init.lua", line=130
18:41:45 [DEBUG] lvim: "enabled format-on-save"       file="lua/lvim/core/autocmds.lua", line=78
18:41:45 [DEBUG] lvim: '["rnix"] is already configured. Ignoring repeated setup call.' file="lua/lvim/lsp/manager.lua", line=71
18:41:45 [DEBUG] lvim: { "rolling" }                  file="lua/lvim/utils/git.lua", line=31
18:41:45 [DEBUG] lvim: { "269a35d" }                  file="lua/lvim/utils/git.lua", line=31
18:42:40 [DEBUG] lvim: "Activated mac keymappings"    file="lvim/lua/lvim/keymappings.lua", line=116
18:42:40 [DEBUG] lvim: "loading plugins configuration" file="lvim/lua/lvim/plugin-loader.lua", line=77
18:42:40 [DEBUG] lvim: "Starting LunarVim"            file="share/lunarvim/lvim/init.lua", line=16
18:42:40 [DEBUG] lvim: "Setting up LSP support"       file="lua/lvim/lsp/init.lua", line=130
18:42:40 [DEBUG] lvim: "enabled format-on-save"       file="lua/lvim/core/autocmds.lua", line=78
18:42:40 [DEBUG] lvim: '["rnix"] is already configured. Ignoring repeated setup call.' file="lua/lvim/lsp/manager.lua", line=71
18:42:40 [DEBUG] lvim: { "rolling" }                  file="lua/lvim/utils/git.lua", line=31
18:42:40 [DEBUG] lvim: { "269a35d" }                  file="lua/lvim/utils/git.lua", line=31
18:47:09 [DEBUG] lvim: "Activated mac keymappings"    file="lvim/lua/lvim/keymappings.lua", line=116
18:47:09 [DEBUG] lvim: "loading plugins configuration" file="lvim/lua/lvim/plugin-loader.lua", line=77
18:47:09 [DEBUG] lvim: "Starting LunarVim"            file="share/lunarvim/lvim/init.lua", line=16
18:47:09 [DEBUG] lvim: "Setting up LSP support"       file="lua/lvim/lsp/init.lua", line=130
18:47:09 [DEBUG] lvim: "enabled format-on-save"       file="lua/lvim/core/autocmds.lua", line=78
18:47:10 [DEBUG] lvim: '["rnix"] is already configured. Ignoring repeated setup call.' file="lua/lvim/lsp/manager.lua", line=71
18:47:10 [DEBUG] lvim: { "rolling" }                  file="lua/lvim/utils/git.lua", line=31
18:47:10 [DEBUG] lvim: { "269a35d" }                  file="lua/lvim/utils/git.lua", line=31
19:00:16 [DEBUG] lvim: "Activated mac keymappings"    file="lvim/lua/lvim/keymappings.lua", line=116
19:00:16 [DEBUG] lvim: "loading plugins configuration" file="lvim/lua/lvim/plugin-loader.lua", line=77
19:00:16 [DEBUG] lvim: "Starting LunarVim"            file="share/lunarvim/lvim/init.lua", line=16
19:00:16 [DEBUG] lvim: "Setting up LSP support"       file="lua/lvim/lsp/init.lua", line=130
19:00:16 [DEBUG] lvim: "enabled format-on-save"       file="lua/lvim/core/autocmds.lua", line=78
19:00:16 [DEBUG] lvim: { "rolling" }                  file="lua/lvim/utils/git.lua", line=31
19:00:16 [DEBUG] lvim: { "269a35d" }                  file="lua/lvim/utils/git.lua", line=31
19:01:32 [DEBUG] lvim: "Activated mac keymappings"    file="lvim/lua/lvim/keymappings.lua", line=116
19:01:32 [DEBUG] lvim: "loading plugins configuration" file="lvim/lua/lvim/plugin-loader.lua", line=77
19:01:32 [DEBUG] lvim: "Starting LunarVim"            file="share/lunarvim/lvim/init.lua", line=16
19:01:32 [DEBUG] lvim: "Setting up LSP support"       file="lua/lvim/lsp/init.lua", line=130
19:01:32 [DEBUG] lvim: "enabled format-on-save"       file="lua/lvim/core/autocmds.lua", line=78
19:01:32 [DEBUG] lvim: '["rnix"] is already configured. Ignoring repeated setup call.' file="lua/lvim/lsp/manager.lua", line=71
19:01:32 [DEBUG] lvim: { "rolling" }                  file="lua/lvim/utils/git.lua", line=31
19:01:32 [DEBUG] lvim: { "269a35d" }                  file="lua/lvim/utils/git.lua", line=31
22:06:00 [DEBUG] lvim: "Activated mac keymappings"    file="lvim/lua/lvim/keymappings.lua", line=116
22:06:00 [DEBUG] lvim: "loading plugins configuration" file="lvim/lua/lvim/plugin-loader.lua", line=77
22:06:00 [DEBUG] lvim: "Starting LunarVim"            file="share/lunarvim/lvim/init.lua", line=16
22:06:00 [DEBUG] lvim: "Setting up LSP support"       file="lua/lvim/lsp/init.lua", line=130
22:06:00 [DEBUG] lvim: "enabled format-on-save"       file="lua/lvim/core/autocmds.lua", line=78
22:06:01 [DEBUG] lvim: { "rolling" }                  file="lua/lvim/utils/git.lua", line=31
22:06:01 [DEBUG] lvim: { "269a35d" }                  file="lua/lvim/utils/git.lua", line=31
22:06:04 [DEBUG] lvim: "Checking for formatter overriding for gopls" file="lua/lvim/lsp/init.lua", line=72
22:08:05 [DEBUG] lvim: "Checking for formatter overriding for gopls" file="lua/lvim/lsp/init.lua", line=72
22:08:06 [DEBUG] lvim: '["gopls"] is already configured. Ignoring repeated setup call.' file="lua/lvim/lsp/manager.lua", line=71
22:35:10 [DEBUG] lvim: "Activated mac keymappings"    file="lvim/lua/lvim/keymappings.lua", line=116
22:35:10 [DEBUG] lvim: "loading plugins configuration" file="lvim/lua/lvim/plugin-loader.lua", line=77
22:35:10 [DEBUG] lvim: "Starting LunarVim"            file="share/lunarvim/lvim/init.lua", line=16
22:35:10 [DEBUG] lvim: "Setting up LSP support"       file="lua/lvim/lsp/init.lua", line=130
22:35:10 [DEBUG] lvim: "enabled format-on-save"       file="lua/lvim/core/autocmds.lua", line=78
22:35:11 [DEBUG] lvim: { "rolling" }                  file="lua/lvim/utils/git.lua", line=31
22:35:11 [DEBUG] lvim: { "269a35d" }                  file="lua/lvim/utils/git.lua", line=31
22:35:16 [DEBUG] lvim: "Checking for formatter overriding for gopls" file="lua/lvim/lsp/init.lua", line=72
22:48:44 [DEBUG] lvim: "Activated mac keymappings"    file="lvim/lua/lvim/keymappings.lua", line=116
22:48:44 [DEBUG] lvim: "loading plugins configuration" file="lvim/lua/lvim/plugin-loader.lua", line=77
22:48:44 [DEBUG] lvim: "Starting LunarVim"            file="share/lunarvim/lvim/init.lua", line=16
22:48:44 [DEBUG] lvim: "Setting up LSP support"       file="lua/lvim/lsp/init.lua", line=130
22:48:44 [DEBUG] lvim: "enabled format-on-save"       file="lua/lvim/core/autocmds.lua", line=78
22:48:44 [DEBUG] lvim: "Automatic server installation detected" file="lua/lvim/lsp/manager.lua", line=94
22:48:44 [DEBUG] lvim: { "rolling" }                  file="lua/lvim/utils/git.lua", line=31
22:48:44 [DEBUG] lvim: { "269a35d" }                  file="lua/lvim/utils/git.lua", line=31
22:48:54 [DEBUG] lvim: "Checking for formatter overriding for tsserver" file="lua/lvim/lsp/init.lua", line=72
22:51:46 [DEBUG] lvim: '["html"] is already configured. Ignoring repeated setup call.' file="lua/lvim/lsp/manager.lua", line=71
23:00:11 [DEBUG] lvim: '["rnix"] is already configured. Ignoring repeated setup call.' file="lua/lvim/lsp/manager.lua", line=71
10:50:03 [DEBUG] lvim: '["gopls"] is already configured. Ignoring repeated setup call.' file="lua/lvim/lsp/manager.lua", line=71
10:50:45 [DEBUG] lvim: '["gopls"] is already configured. Ignoring repeated setup call.' file="lua/lvim/lsp/manager.lua", line=71
13:13:09 [DEBUG] lvim: '["gopls"] is already configured. Ignoring repeated setup call.' file="lua/lvim/lsp/manager.lua", line=71
13:20:39 [DEBUG] lvim: '["gopls"] is already configured. Ignoring repeated setup call.' file="lua/lvim/lsp/manager.lua", line=71
13:23:33 [DEBUG] lvim: '["gopls"] is already configured. Ignoring repeated setup call.' file="lua/lvim/lsp/manager.lua", line=71
13:25:46 [DEBUG] lvim: "Checking for formatter overriding for gopls" file="lua/lvim/lsp/init.lua", line=72
13:26:08 [DEBUG] lvim: '["gopls"] is already configured. Ignoring repeated setup call.' file="lua/lvim/lsp/manager.lua", line=71
13:26:08 [DEBUG] lvim: "Checking for formatter overriding for gopls" file="lua/lvim/lsp/init.lua", line=72
13:26:29 [DEBUG] lvim: '["gopls"] is already configured. Ignoring repeated setup call.' file="lua/lvim/lsp/manager.lua", line=71
14:51:58 [DEBUG] lvim: "Activated mac keymappings"    file="lvim/lua/lvim/keymappings.lua", line=116
14:51:58 [DEBUG] lvim: "loading plugins configuration" file="lvim/lua/lvim/plugin-loader.lua", line=77
14:51:58 [DEBUG] lvim: "Starting LunarVim"            file="share/lunarvim/lvim/init.lua", line=16
14:51:58 [DEBUG] lvim: "Setting up LSP support"       file="lua/lvim/lsp/init.lua", line=130
14:51:58 [DEBUG] lvim: "enabled format-on-save"       file="lua/lvim/core/autocmds.lua", line=78
14:51:59 [DEBUG] lvim: { "rolling" }                  file="lua/lvim/utils/git.lua", line=31
14:51:59 [DEBUG] lvim: { "269a35d" }                  file="lua/lvim/utils/git.lua", line=31
14:52:18 [DEBUG] lvim: "Checking for formatter overriding for terraformls" file="lua/lvim/lsp/init.lua", line=72
15:03:31 [DEBUG] lvim: '["terraformls"] is already configured. Ignoring repeated setup call.' file="lua/lvim/lsp/manager.lua", line=71
15:05:12 [DEBUG] lvim: '["terraformls"] is already configured. Ignoring repeated setup call.' file="lua/lvim/lsp/manager.lua", line=71
15:17:21 [DEBUG] lvim: '["terraformls"] is already configured. Ignoring repeated setup call.' file="lua/lvim/lsp/manager.lua", line=71
15:22:33 [DEBUG] lvim: '["terraformls"] is already configured. Ignoring repeated setup call.' file="lua/lvim/lsp/manager.lua", line=71
15:25:01 [DEBUG] lvim: '["terraformls"] is already configured. Ignoring repeated setup call.' file="lua/lvim/lsp/manager.lua", line=71
15:25:44 [DEBUG] lvim: '["terraformls"] is already configured. Ignoring repeated setup call.' file="lua/lvim/lsp/manager.lua", line=71
15:37:12 [DEBUG] lvim: '["terraformls"] is already configured. Ignoring repeated setup call.' file="lua/lvim/lsp/manager.lua", line=71
18:35:06 [DEBUG] lvim: "Activated mac keymappings"    file="lvim/lua/lvim/keymappings.lua", line=116
18:35:06 [DEBUG] lvim: "loading plugins configuration" file="lvim/lua/lvim/plugin-loader.lua", line=77
18:35:06 [DEBUG] lvim: "Starting LunarVim"            file="share/lunarvim/lvim/init.lua", line=16
18:35:06 [DEBUG] lvim: "Setting up LSP support"       file="lua/lvim/lsp/init.lua", line=130
18:35:06 [DEBUG] lvim: "enabled format-on-save"       file="lua/lvim/core/autocmds.lua", line=78
18:35:06 [DEBUG] lvim: { "rolling" }                  file="lua/lvim/utils/git.lua", line=31
18:35:07 [DEBUG] lvim: { "269a35d" }                  file="lua/lvim/utils/git.lua", line=31
20:47:07 [DEBUG] lvim: '["gopls"] is already configured. Ignoring repeated setup call.' file="lua/lvim/lsp/manager.lua", line=71
01:36:27 [DEBUG] lvim: "Activated mac keymappings"    file="lvim/lua/lvim/keymappings.lua", line=116
01:36:27 [DEBUG] lvim: "loading plugins configuration" file="lvim/lua/lvim/plugin-loader.lua", line=77
01:36:27 [DEBUG] lvim: "Starting LunarVim"            file="share/lunarvim/lvim/init.lua", line=16
01:36:27 [DEBUG] lvim: "Setting up LSP support"       file="lua/lvim/lsp/init.lua", line=130
01:36:27 [DEBUG] lvim: "enabled format-on-save"       file="lua/lvim/core/autocmds.lua", line=78
01:36:27 [DEBUG] lvim: { "rolling" }                  file="lua/lvim/utils/git.lua", line=31
01:36:28 [DEBUG] lvim: { "269a35d" }                  file="lua/lvim/utils/git.lua", line=31
15:45:33 [DEBUG] lvim: "Activated mac keymappings"    file="lvim/lua/lvim/keymappings.lua", line=116
15:45:33 [DEBUG] lvim: "loading plugins configuration" file="lvim/lua/lvim/plugin-loader.lua", line=77
15:45:33 [DEBUG] lvim: "Starting LunarVim"            file="share/lunarvim/lvim/init.lua", line=16
15:45:33 [DEBUG] lvim: "Setting up LSP support"       file="lua/lvim/lsp/init.lua", line=130
15:45:33 [DEBUG] lvim: "enabled format-on-save"       file="lua/lvim/core/autocmds.lua", line=78
15:45:33 [DEBUG] lvim: { "rolling" }                  file="lua/lvim/utils/git.lua", line=31
15:45:33 [DEBUG] lvim: { "269a35d" }                  file="lua/lvim/utils/git.lua", line=31
15:45:35 [DEBUG] lvim: "Checking for formatter overriding for terraformls" file="lua/lvim/lsp/init.lua", line=72
15:46:33 [DEBUG] lvim: '["terraformls"] is already configured. Ignoring repeated setup call.' file="lua/lvim/lsp/manager.lua", line=71
15:52:07 [DEBUG] lvim: '["terraformls"] is already configured. Ignoring repeated setup call.' file="lua/lvim/lsp/manager.lua", line=71
17:20:10 [DEBUG] lvim: "Activated mac keymappings"    file="lvim/lua/lvim/keymappings.lua", line=116
17:20:10 [DEBUG] lvim: "loading plugins configuration" file="lvim/lua/lvim/plugin-loader.lua", line=77
17:20:10 [DEBUG] lvim: "Starting LunarVim"            file="share/lunarvim/lvim/init.lua", line=16
17:20:10 [DEBUG] lvim: "Setting up LSP support"       file="lua/lvim/lsp/init.lua", line=130
17:20:10 [DEBUG] lvim: "enabled format-on-save"       file="lua/lvim/core/autocmds.lua", line=78
17:20:10 [DEBUG] lvim: '["rnix"] is already configured. Ignoring repeated setup call.' file="lua/lvim/lsp/manager.lua", line=71
17:20:11 [DEBUG] lvim: { "rolling" }                  file="lua/lvim/utils/git.lua", line=31
17:20:11 [DEBUG] lvim: { "269a35d" }                  file="lua/lvim/utils/git.lua", line=31
17:55:37 [DEBUG] lvim: "Activated mac keymappings"    file="lvim/lua/lvim/keymappings.lua", line=116
17:55:37 [DEBUG] lvim: "loading plugins configuration" file="lvim/lua/lvim/plugin-loader.lua", line=77
17:55:37 [DEBUG] lvim: "Starting LunarVim"            file="share/lunarvim/lvim/init.lua", line=16
17:55:37 [DEBUG] lvim: "Setting up LSP support"       file="lua/lvim/lsp/init.lua", line=130
17:55:37 [DEBUG] lvim: "enabled format-on-save"       file="lua/lvim/core/autocmds.lua", line=78
17:55:38 [DEBUG] lvim: { "rolling" }                  file="lua/lvim/utils/git.lua", line=31
17:55:38 [DEBUG] lvim: { "269a35d" }                  file="lua/lvim/utils/git.lua", line=31
12:44:22 [DEBUG] lvim: "Activated mac keymappings"    file="lvim/lua/lvim/keymappings.lua", line=116
12:44:22 [DEBUG] lvim: "loading plugins configuration" file="lvim/lua/lvim/plugin-loader.lua", line=77
12:44:22 [DEBUG] lvim: "Starting LunarVim"            file="share/lunarvim/lvim/init.lua", line=16
12:44:22 [DEBUG] lvim: "Setting up LSP support"       file="lua/lvim/lsp/init.lua", line=130
12:44:22 [DEBUG] lvim: "enabled format-on-save"       file="lua/lvim/core/autocmds.lua", line=78
12:44:23 [DEBUG] lvim: "Using custom configuration for requested server: yamlls" file="lua/lvim/lsp/manager.lua", line=33
12:44:23 [DEBUG] lvim: { "rolling" }                  file="lua/lvim/utils/git.lua", line=31
12:44:23 [DEBUG] lvim: { "269a35d" }                  file="lua/lvim/utils/git.lua", line=31
13:39:01 [DEBUG] lvim: "Activated mac keymappings"    file="lvim/lua/lvim/keymappings.lua", line=116
13:39:01 [DEBUG] lvim: "loading plugins configuration" file="lvim/lua/lvim/plugin-loader.lua", line=77
13:39:01 [DEBUG] lvim: "Starting LunarVim"            file="share/lunarvim/lvim/init.lua", line=16
13:39:01 [DEBUG] lvim: "Setting up LSP support"       file="lua/lvim/lsp/init.lua", line=130
13:39:01 [DEBUG] lvim: "enabled format-on-save"       file="lua/lvim/core/autocmds.lua", line=78
13:39:01 [DEBUG] lvim: { "rolling" }                  file="lua/lvim/utils/git.lua", line=31
13:39:01 [DEBUG] lvim: { "269a35d" }                  file="lua/lvim/utils/git.lua", line=31
13:40:42 [DEBUG] lvim: "Checking for formatter overriding for dockerls" file="lua/lvim/lsp/init.lua", line=72
15:57:09 [DEBUG] lvim: "Activated mac keymappings"    file="lvim/lua/lvim/keymappings.lua", line=116
15:57:09 [DEBUG] lvim: "loading plugins configuration" file="lvim/lua/lvim/plugin-loader.lua", line=77
15:57:09 [DEBUG] lvim: "Starting LunarVim"            file="share/lunarvim/lvim/init.lua", line=16
15:57:09 [DEBUG] lvim: "Setting up LSP support"       file="lua/lvim/lsp/init.lua", line=130
15:57:09 [DEBUG] lvim: "enabled format-on-save"       file="lua/lvim/core/autocmds.lua", line=78
15:57:09 [DEBUG] lvim: { "rolling" }                  file="lua/lvim/utils/git.lua", line=31
15:57:09 [DEBUG] lvim: { "269a35d" }                  file="lua/lvim/utils/git.lua", line=31
16:17:28 [DEBUG] lvim: "Activated mac keymappings"    file="lvim/lua/lvim/keymappings.lua", line=116
16:17:28 [DEBUG] lvim: "loading plugins configuration" file="lvim/lua/lvim/plugin-loader.lua", line=77
16:17:28 [DEBUG] lvim: "Starting LunarVim"            file="share/lunarvim/lvim/init.lua", line=16
16:17:28 [DEBUG] lvim: "Setting up LSP support"       file="lua/lvim/lsp/init.lua", line=130
16:17:28 [DEBUG] lvim: "enabled format-on-save"       file="lua/lvim/core/autocmds.lua", line=78
16:17:29 [DEBUG] lvim: "Using custom configuration for requested server: yamlls" file="lua/lvim/lsp/manager.lua", line=33
16:17:29 [DEBUG] lvim: { "rolling" }                  file="lua/lvim/utils/git.lua", line=31
16:17:29 [DEBUG] lvim: { "269a35d" }                  file="lua/lvim/utils/git.lua", line=31
16:21:43 [DEBUG] lvim: "Activated mac keymappings"    file="lvim/lua/lvim/keymappings.lua", line=116
16:21:43 [DEBUG] lvim: "loading plugins configuration" file="lvim/lua/lvim/plugin-loader.lua", line=77
16:21:43 [DEBUG] lvim: "Starting LunarVim"            file="share/lunarvim/lvim/init.lua", line=16
16:21:43 [DEBUG] lvim: "Setting up LSP support"       file="lua/lvim/lsp/init.lua", line=130
16:21:43 [DEBUG] lvim: "enabled format-on-save"       file="lua/lvim/core/autocmds.lua", line=78
16:21:43 [DEBUG] lvim: { "rolling" }                  file="lua/lvim/utils/git.lua", line=31
16:21:43 [DEBUG] lvim: { "269a35d" }                  file="lua/lvim/utils/git.lua", line=31
22:23:33 [DEBUG] lvim: "Activated mac keymappings"    file="lvim/lua/lvim/keymappings.lua", line=116
22:23:33 [DEBUG] lvim: "loading plugins configuration" file="lvim/lua/lvim/plugin-loader.lua", line=77
22:23:33 [DEBUG] lvim: "Starting LunarVim"            file="share/lunarvim/lvim/init.lua", line=16
22:23:33 [DEBUG] lvim: "Setting up LSP support"       file="lua/lvim/lsp/init.lua", line=130
22:23:33 [DEBUG] lvim: "enabled format-on-save"       file="lua/lvim/core/autocmds.lua", line=78
22:23:33 [DEBUG] lvim: { "rolling" }                  file="lua/lvim/utils/git.lua", line=31
22:23:33 [DEBUG] lvim: { "269a35d" }                  file="lua/lvim/utils/git.lua", line=31
15:39:25 [DEBUG] lvim: "Activated mac keymappings"    file="lvim/lua/lvim/keymappings.lua", line=116
15:39:25 [DEBUG] lvim: "loading plugins configuration" file="lvim/lua/lvim/plugin-loader.lua", line=77
15:39:25 [DEBUG] lvim: "Starting LunarVim"            file="share/lunarvim/lvim/init.lua", line=16
15:39:25 [DEBUG] lvim: "Setting up LSP support"       file="lua/lvim/lsp/init.lua", line=130
15:39:25 [DEBUG] lvim: "enabled format-on-save"       file="lua/lvim/core/autocmds.lua", line=78
15:39:25 [DEBUG] lvim: '["rnix"] is already configured. Ignoring repeated setup call.' file="lua/lvim/lsp/manager.lua", line=71
15:39:26 [DEBUG] lvim: { "rolling" }                  file="lua/lvim/utils/git.lua", line=31
15:39:26 [DEBUG] lvim: { "269a35d" }                  file="lua/lvim/utils/git.lua", line=31
18:12:47 [DEBUG] lvim: "Activated mac keymappings"    file="lvim/lua/lvim/keymappings.lua", line=116
18:12:47 [DEBUG] lvim: "loading plugins configuration" file="lvim/lua/lvim/plugin-loader.lua", line=77
18:12:47 [DEBUG] lvim: "Starting LunarVim"            file="share/lunarvim/lvim/init.lua", line=16
18:12:47 [DEBUG] lvim: "Setting up LSP support"       file="lua/lvim/lsp/init.lua", line=130
18:12:47 [DEBUG] lvim: "enabled format-on-save"       file="lua/lvim/core/autocmds.lua", line=78
18:12:48 [DEBUG] lvim: '["rnix"] is already configured. Ignoring repeated setup call.' file="lua/lvim/lsp/manager.lua", line=71
18:12:48 [DEBUG] lvim: { "rolling" }                  file="lua/lvim/utils/git.lua", line=31
18:12:48 [DEBUG] lvim: { "269a35d" }                  file="lua/lvim/utils/git.lua", line=31
20:05:43 [DEBUG] lvim: "Activated mac keymappings"    file="lvim/lua/lvim/keymappings.lua", line=116
20:05:43 [DEBUG] lvim: "loading plugins configuration" file="lvim/lua/lvim/plugin-loader.lua", line=77
20:05:43 [DEBUG] lvim: "Starting LunarVim"            file="share/lunarvim/lvim/init.lua", line=16
20:05:43 [DEBUG] lvim: "Setting up LSP support"       file="lua/lvim/lsp/init.lua", line=130
20:05:43 [DEBUG] lvim: "enabled format-on-save"       file="lua/lvim/core/autocmds.lua", line=78
20:05:43 [DEBUG] lvim: '["rnix"] is already configured. Ignoring repeated setup call.' file="lua/lvim/lsp/manager.lua", line=71
20:05:43 [DEBUG] lvim: { "rolling" }                  file="lua/lvim/utils/git.lua", line=31
20:05:43 [DEBUG] lvim: { "269a35d" }                  file="lua/lvim/utils/git.lua", line=31
23:15:17 [DEBUG] lvim: "Activated mac keymappings"    file="lvim/lua/lvim/keymappings.lua", line=116
23:15:17 [DEBUG] lvim: "loading plugins configuration" file="lvim/lua/lvim/plugin-loader.lua", line=77
23:15:17 [DEBUG] lvim: "Starting LunarVim"            file="share/lunarvim/lvim/init.lua", line=16
23:15:17 [DEBUG] lvim: "Setting up LSP support"       file="lua/lvim/lsp/init.lua", line=130
23:15:17 [DEBUG] lvim: "enabled format-on-save"       file="lua/lvim/core/autocmds.lua", line=78
23:15:18 [DEBUG] lvim: { "rolling" }                  file="lua/lvim/utils/git.lua", line=31
23:15:18 [DEBUG] lvim: { "269a35d" }                  file="lua/lvim/utils/git.lua", line=31
23:51:54 [DEBUG] lvim: "Activated mac keymappings"    file="lvim/lua/lvim/keymappings.lua", line=116
23:51:54 [DEBUG] lvim: "loading plugins configuration" file="lvim/lua/lvim/plugin-loader.lua", line=77
23:51:54 [DEBUG] lvim: "Starting LunarVim"            file="share/lunarvim/lvim/init.lua", line=16
23:51:54 [DEBUG] lvim: "Setting up LSP support"       file="lua/lvim/lsp/init.lua", line=130
23:51:54 [DEBUG] lvim: "enabled format-on-save"       file="lua/lvim/core/autocmds.lua", line=78
23:51:54 [DEBUG] lvim: { "rolling" }                  file="lua/lvim/utils/git.lua", line=31
23:51:54 [DEBUG] lvim: { "269a35d" }                  file="lua/lvim/utils/git.lua", line=31
23:54:08 [DEBUG] lvim: "Activated mac keymappings"    file="lvim/lua/lvim/keymappings.lua", line=116
23:54:08 [DEBUG] lvim: "loading plugins configuration" file="lvim/lua/lvim/plugin-loader.lua", line=77
23:54:08 [DEBUG] lvim: "Starting LunarVim"            file="share/lunarvim/lvim/init.lua", line=16
23:54:08 [DEBUG] lvim: "Setting up LSP support"       file="lua/lvim/lsp/init.lua", line=130
23:54:08 [DEBUG] lvim: "enabled format-on-save"       file="lua/lvim/core/autocmds.lua", line=78
23:54:08 [DEBUG] lvim: { "rolling" }                  file="lua/lvim/utils/git.lua", line=31
23:54:08 [DEBUG] lvim: { "269a35d" }                  file="lua/lvim/utils/git.lua", line=31
23:59:38 [DEBUG] lvim: "Activated mac keymappings"    file="lvim/lua/lvim/keymappings.lua", line=116
23:59:38 [DEBUG] lvim: "loading plugins configuration" file="lvim/lua/lvim/plugin-loader.lua", line=77
23:59:38 [DEBUG] lvim: "Starting LunarVim"            file="share/lunarvim/lvim/init.lua", line=16
23:59:38 [DEBUG] lvim: "Setting up LSP support"       file="lua/lvim/lsp/init.lua", line=130
23:59:38 [DEBUG] lvim: "enabled format-on-save"       file="lua/lvim/core/autocmds.lua", line=78
23:59:38 [DEBUG] lvim: { "rolling" }                  file="lua/lvim/utils/git.lua", line=31
23:59:38 [DEBUG] lvim: { "269a35d" }                  file="lua/lvim/utils/git.lua", line=31
00:00:11 [DEBUG] lvim: "Activated mac keymappings"    file="lvim/lua/lvim/keymappings.lua", line=116
00:00:11 [DEBUG] lvim: "loading plugins configuration" file="lvim/lua/lvim/plugin-loader.lua", line=77
00:00:11 [DEBUG] lvim: "Starting LunarVim"            file="share/lunarvim/lvim/init.lua", line=16
00:00:11 [DEBUG] lvim: "Setting up LSP support"       file="lua/lvim/lsp/init.lua", line=130
00:00:11 [DEBUG] lvim: "enabled format-on-save"       file="lua/lvim/core/autocmds.lua", line=78
00:00:11 [DEBUG] lvim: { "rolling" }                  file="lua/lvim/utils/git.lua", line=31
00:00:11 [DEBUG] lvim: { "269a35d" }                  file="lua/lvim/utils/git.lua", line=31
02:15:22 [DEBUG] lvim: "Activated mac keymappings"    file="lvim/lua/lvim/keymappings.lua", line=116
02:15:22 [DEBUG] lvim: "loading plugins configuration" file="lvim/lua/lvim/plugin-loader.lua", line=77
02:15:22 [DEBUG] lvim: "Starting LunarVim"            file="share/lunarvim/lvim/init.lua", line=16
02:15:22 [DEBUG] lvim: "Setting up LSP support"       file="lua/lvim/lsp/init.lua", line=130
02:15:22 [DEBUG] lvim: "enabled format-on-save"       file="lua/lvim/core/autocmds.lua", line=78
02:15:22 [DEBUG] lvim: '["rnix"] is already configured. Ignoring repeated setup call.' file="lua/lvim/lsp/manager.lua", line=71
02:15:22 [DEBUG] lvim: { "rolling" }                  file="lua/lvim/utils/git.lua", line=31
02:15:22 [DEBUG] lvim: { "269a35d" }                  file="lua/lvim/utils/git.lua", line=31
15:45:20 [DEBUG] lvim: "Activated mac keymappings"    file="lvim/lua/lvim/keymappings.lua", line=116
15:45:20 [DEBUG] lvim: "loading plugins configuration" file="lvim/lua/lvim/plugin-loader.lua", line=77
15:45:20 [DEBUG] lvim: "Starting LunarVim"            file="share/lunarvim/lvim/init.lua", line=16
15:45:20 [DEBUG] lvim: "Setting up LSP support"       file="lua/lvim/lsp/init.lua", line=130
15:45:20 [DEBUG] lvim: "enabled format-on-save"       file="lua/lvim/core/autocmds.lua", line=78
15:45:20 [DEBUG] lvim: '["rnix"] is already configured. Ignoring repeated setup call.' file="lua/lvim/lsp/manager.lua", line=71
15:45:20 [DEBUG] lvim: { "rolling" }                  file="lua/lvim/utils/git.lua", line=31
15:45:20 [DEBUG] lvim: { "269a35d" }                  file="lua/lvim/utils/git.lua", line=31
19:25:02 [DEBUG] lvim: "Activated mac keymappings"    file="lvim/lua/lvim/keymappings.lua", line=116
19:25:02 [DEBUG] lvim: "loading plugins configuration" file="lvim/lua/lvim/plugin-loader.lua", line=77
19:25:02 [DEBUG] lvim: "Starting LunarVim"            file="share/lunarvim/lvim/init.lua", line=16
19:25:02 [DEBUG] lvim: "Setting up LSP support"       file="lua/lvim/lsp/init.lua", line=130
19:25:02 [DEBUG] lvim: "enabled format-on-save"       file="lua/lvim/core/autocmds.lua", line=78
19:25:02 [DEBUG] lvim: { "rolling" }                  file="lua/lvim/utils/git.lua", line=31
19:25:02 [DEBUG] lvim: { "269a35d" }                  file="lua/lvim/utils/git.lua", line=31
19:25:50 [DEBUG] lvim: "Activated mac keymappings"    file="lvim/lua/lvim/keymappings.lua", line=116
19:25:50 [DEBUG] lvim: "loading plugins configuration" file="lvim/lua/lvim/plugin-loader.lua", line=77
19:25:50 [DEBUG] lvim: "Starting LunarVim"            file="share/lunarvim/lvim/init.lua", line=16
19:25:50 [DEBUG] lvim: "Setting up LSP support"       file="lua/lvim/lsp/init.lua", line=130
19:25:50 [DEBUG] lvim: "enabled format-on-save"       file="lua/lvim/core/autocmds.lua", line=78
19:25:50 [DEBUG] lvim: { "rolling" }                  file="lua/lvim/utils/git.lua", line=31
19:25:50 [DEBUG] lvim: { "269a35d" }                  file="lua/lvim/utils/git.lua", line=31
19:26:01 [DEBUG] lvim: "Activated mac keymappings"    file="lvim/lua/lvim/keymappings.lua", line=116
19:26:01 [DEBUG] lvim: "loading plugins configuration" file="lvim/lua/lvim/plugin-loader.lua", line=77
19:26:01 [DEBUG] lvim: "Starting LunarVim"            file="share/lunarvim/lvim/init.lua", line=16
19:26:01 [DEBUG] lvim: "Setting up LSP support"       file="lua/lvim/lsp/init.lua", line=130
19:26:01 [DEBUG] lvim: "enabled format-on-save"       file="lua/lvim/core/autocmds.lua", line=78
19:26:01 [DEBUG] lvim: { "rolling" }                  file="lua/lvim/utils/git.lua", line=31
19:26:01 [DEBUG] lvim: { "269a35d" }                  file="lua/lvim/utils/git.lua", line=31
18:17:51 [DEBUG] lvim: "Activated mac keymappings"    file="lvim/lua/lvim/keymappings.lua", line=116
18:17:51 [DEBUG] lvim: "loading plugins configuration" file="lvim/lua/lvim/plugin-loader.lua", line=77
18:17:51 [DEBUG] lvim: "Starting LunarVim"            file="share/lunarvim/lvim/init.lua", line=16
18:17:51 [DEBUG] lvim: "Setting up LSP support"       file="lua/lvim/lsp/init.lua", line=130
18:17:51 [DEBUG] lvim: "enabled format-on-save"       file="lua/lvim/core/autocmds.lua", line=78
18:17:52 [DEBUG] lvim: { "rolling" }                  file="lua/lvim/utils/git.lua", line=31
18:17:52 [DEBUG] lvim: { "269a35d" }                  file="lua/lvim/utils/git.lua", line=31
18:21:19 [DEBUG] lvim: "Activated mac keymappings"    file="lvim/lua/lvim/keymappings.lua", line=116
18:21:19 [DEBUG] lvim: "loading plugins configuration" file="lvim/lua/lvim/plugin-loader.lua", line=77
18:21:19 [DEBUG] lvim: "Starting LunarVim"            file="share/lunarvim/lvim/init.lua", line=16
18:21:19 [DEBUG] lvim: "Setting up LSP support"       file="lua/lvim/lsp/init.lua", line=130
18:21:19 [DEBUG] lvim: "enabled format-on-save"       file="lua/lvim/core/autocmds.lua", line=78
18:21:19 [DEBUG] lvim: { "rolling" }                  file="lua/lvim/utils/git.lua", line=31
18:21:19 [DEBUG] lvim: { "269a35d" }                  file="lua/lvim/utils/git.lua", line=31
18:21:25 [DEBUG] lvim: "Starting pre-update hook"     file="lua/lvim/utils/hooks.lua", line=7
18:21:25 [INFO ] lvim: "Checking for updates"         file="lua/lvim/utils/git.lua", line=55
18:21:28 [DEBUG] lvim: { "From github.com:/lunarvim/lunarvim", "   269a35d..9eb8479  rolling    -> origin/rolling" } file="lua/lvim/utils/git.lua", line=27
18:21:28 [DEBUG] lvim: { "Updating 269a35d..9eb8479", "Fast-forward", " .github/ISSUE_TEMPLATE/general-issue-form.yaml |   4 +-", " .github/ISSUE_TEMPLATE/lsp-issue-form.yaml     |   4 +-", " Makefile                                       |   2 +-", " README.md                                      |   8 +-", " lua/lvim/bootstrap.lua                         |   4 +-", " lua/lvim/core/autopairs.lua                    |  20 ---", " lua/lvim/core/info.lua                         |  34 ++---", " lua/lvim/core/log.lua                          |   2 +-", " lua/lvim/core/lualine/components.lua           |   4 +-", " lua/lvim/lsp/config.lua                        |   7 +-", " lua/lvim/lsp/providers/jsonls.lua              | 186 +------------------------", " lua/lvim/plugins.lua                           |  61 ++++----", " lua/lvim/utils/git.lua                         |   2 +-", " utils/installer/install.ps1                    |  11 +-", " utils/installer/install.sh                     |   4 +-", " 15 files changed, 89 insertions(+), 264 deletions(-)" } file="lua/lvim/utils/git.lua", line=31
18:21:28 [DEBUG] lvim: "Starting post-update hook"    file="lua/lvim/utils/hooks.lua", line=46
18:21:28 [TRACE] lvim: "Cache invalidated for core modules: { lvim.core.bufferline, lvim.core.nvimtree, lvim.core.lualine.conditions, lvim.core.lualine.components, lvim.core.terminal, lvim.core.notify, lvim.core.which-key, lvim.core.lualine.styles, lvim.lsp.manager, lvim.core.treesitter, lvim.core.gitsigns, lvim.core.log, lvim.core.commands, lvim.lsp, lvim.lsp.utils, lvim.core.dap, lvim.core.lualine, lvim.core.cmp, lvim.core.telescope, lvim.lsp.null-ls, lvim.core.telescope.custom-finders, lvim.lsp.config, lvim.core.lualine.colors, lvim.core.autopairs, lvim.core.autocmds, lvim.core.builtins, lvim.core.lualine.utils, lvim.core.project, lvim.core.comment, lvim.core.dashboard, lvim.lsp.handlers }" file="lua/lvim/utils/hooks.lua", line=41
18:21:29 [DEBUG] lvim: "Updating core plugins"        file="lua/lvim/utils/hooks.lua", line=49
18:21:29 [TRACE] lvim: 'Syncing core plugins: [""]'   file="lvim/lua/lvim/plugin-loader.lua", line=119
18:21:38 [INFO ] lvim: "Reloaded configuration"       file="lua/lvim/utils/hooks.lua", line=17
18:21:42 [TRACE] lvim: 'Syncing core plugins: [""]'   file="lvim/lua/lvim/plugin-loader.lua", line=119
18:22:34 [TRACE] lvim: 'Syncing core plugins: [""]'   file="lvim/lua/lvim/plugin-loader.lua", line=119
18:23:09 [TRACE] lvim: 'Syncing core plugins: [""]'   file="lvim/lua/lvim/plugin-loader.lua", line=119
```

### Screenshots

https://user-images.githubusercontent.com/1226384/155708310-305354df-8c0c-4765-8dca-5fa33f44c6fe.mov

**Comment by kylo252** [comment]
The thing is that nvim-tree is through a refactor phase, so this may already be fixed with #2315, since this commit looks relevant, https://github.com/kyazdani42/nvim-tree.lua/commit/19346da6e1f87cc0841efc9aa6ccc5be273c33a1

Otherwise, I couldn't really follow what's going on in the screencast because the keys are on the opposite side and the font is a bit too small to read unless in full-screen 😅

**Comment by kylo252** [comment]
cc: our resident mac expert, @abzcoding

**Comment by abzcoding** [comment]
@kylo252 sadly i can't reproduce this on my own mac

**Comment by sagikazarmark** [comment]
I tried upgrading to the latest rolling version, cleaning the cache and everything else that came to my mind. I can still reproduce the following:

```shell
mkdir tmp
cd tmp
touch testfile
vim
```

- Open the file
- Write something in the file
- Save the file
- Open nvim tree
- Hit `ZQ`

Result: the file seems to be closed, but Vim stays open and nvim tree becomes fullscreen. If I close nvim tree, the file appears open again.

I created another screen recording (with keycastr closer to the prompt):

https://user-images.githubusercontent.com/1226384/155888946-e9da68a3-af3e-4e14-8afe-16e7e59bd8e6.mov

I checked the configuration, but I couldn't find anything related, but here it is: https://gist.github.com/sagikazarmark/4519acade3a4fdb1470acb1cef7d4e68

**Comment by kylo252** [comment]
I'm not really sure about the use-case here, since I usually only use either a buffer command or completely close all `:qa!`

Please give [buf_kill](https://github.com/LunarVim/LunarVim/blob/2a9f9998aca359a41eefe3a1c429d049a5a1806b/lua/lvim/core/bufferline.lua#L142-L147) a try
```lua
-- this will execute `:bd!` for the current buffer
require("lvim.core.bufferline").buf_kill("bd", 0, true)
```

**Comment by ck3mp3r** [comment]
I think the expected behaviour here is not to have the tree take up the entire window, but rather have either the dashboard appear again or an empty buffer... I've come across this numerous times as well and it is not a dealbreaker but nonetheless annoying...

**Comment by kylo252** [comment]
I just tried what you described but I don't quite see it, but that could be because I'm using alpha.nvim instead. Could you try disabling dashboard and see if there's a difference?

--- 

Alternatively, this might be completely controllable by nvim-tree, please try experimenting with some of these values to see which ones makes sense for your workflow
```lua
 -- default values
lvim.builtin.nvimtree.setup.actions.open_file.quit_on_open = false
lvim.builtin.nvimtree.setup.hijack_unnamed_buffer_when_opening = false
lvim.builtin.nvimtree.setup.hijack_directories.auto_open = true
lvim.builtin.nvimtree.setup.open_on_setup = false
lvim.builtin.nvimtree.setup.open_on_tab = false
```
refs: 
- https://github.com/kyazdani42/nvim-tree.lua/blob/9b03ab40e843e251f01bccec2eca5ea9dcdebc0d/doc/nvim-tree-lua.txt#L67
- https://github.com/LunarVim/LunarVim/blob/5fd8b4b72642ab94c33bb6e706617a554c0d2f19/lua/lvim/core/nvimtree.lua#L23-L9

**Comment by kylo252** [comment]
Please let me know if you're still having problems with this.

**Comment by martin-braun** [comment]
@kylo252 Please re-open this. I have the very same problem. I'm using a fresh LunarVim installation and only did minor adjustments to the config.lua:

```lua
-- general
lvim.log.level = "warn"
lvim.format_on_save = true
lvim.colorscheme = "tokyonight-moon"

-- keymappings [view all the defaults by pressing <leader>Lk]
lvim.leader = "space"
lvim.keys.normal_mode["<C-s>"] = ":w<cr>"
lvim.keys.normal_mode["<C-a>"] = "gg<S-v>G"
lvim.keys.normal_mode["<C-j>"] = ":bnext<cr>"
lvim.keys.normal_mode["<C-k>"] = ":bprev<cr>"

-- TODO: User Config for predefined plugins
-- After changing plugin config exit and reopen LunarVim, Run :PackerInstall :PackerCompile
lvim.builtin.alpha.active = true
lvim.builtin.alpha.mode = "dashboard"
lvim.builtin.notify.active = true
lvim.builtin.terminal.active = true
lvim.builtin.nvimtree.setup.view.side = "left"
lvim.builtin.nvimtree.setup.renderer.icons.show.git = false

-- if you don't want all the parsers change this to a table of the ones you want
lvim.builtin.treesitter.ensure_installed = {
  "bash",
  "c",
  "javascript",
  "json",
  "lua",
  "python",
  "typescript",
  "tsx",
  "css",
  "rust",
  "java",
  "yaml",
}

lvim.builtin.treesitter.ignore_install = { "haskell" }
lvim.builtin.treesitter.highlight.enabled = true

-- Additional Plugins
lvim.plugins = {
  { "folke/tokyonight.nvim" },
  { "f-person/auto-dark-mode.nvim" },
  -- {
  --   "folke/trouble.nvim",
  --   cmd = "TroubleToggle",
  -- },
}

-- Plugin Setup

local auto_dark_mode = require('auto-dark-mode')
auto_dark_mode.setup({
  update_interval = 1000,
  set_dark_mode = function()
    vim.api.nvim_set_option('background', 'dark')
    vim.cmd('colorscheme tokyonight-moon')
  end,
  set_light_mode = function()
    vim.api.nvim_set_option('background', 'light')
    vim.cmd('colorscheme tokyonight-day')
  end,
})
auto_dark_mode.init()

-- Autocommands (https://neovim.io/doc/user/autocmd.html)
-- turn off paste mode when leaving insert
vim.api.nvim_create_autocmd("InsertLeave", {
  pattern = '*',
  command = "set nopaste"
})

-- neovim
vim.opt.mouse = "c"
vim.opt.relativenumber = true
vim.opt.scrolloff = 3
vim.opt.showmode = true
```

Presentation with pressed keys: 

![2022-09-23 10 30 42 AM](https://user-images.githubusercontent.com/24259245/191921824-3f850521-a064-42e4-89f7-90dea838d871.gif)

You can see how I can close the 2nd tab with `<leader> c` and the other two tabs stay open. As soon as I close the first tab though, the explorer window maxes in size. It's very frustrating.

```

    __                          _    ___         
   / /   __  ______  ____ _____| |  / (_)___ ___ 
  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
 / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 


Buffer info
* filetype:                NvimTree
* bufnr:                   59
* treesitter status:       inactive

Active client(s)

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, golangci_lint_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, rome, reason_ls, solang, sorbet, sourcery, sqlls, sqls, stylelint_lsp, tflint, svlangserver, verible, vuels]

Formatters info
* Active: 
* Supported: []

Linters info
* Active: 
* Supported: []

Code actions info
* Active: 
```

Yes I know, things are inactive right now, still need to figure out what's going on with treesitter, but that's a different story.

The issue is not happening when the explorer window is hidden, so it seems the NvimTree thinks all tabs are closed when the first tab is closed. I will probably circumvent the issue by hiding the explorer in the first place.

Can I provide anything to help to track down the issue?

**Comment by kylo252** [comment]
@martin-braun, there are a lot of changes coming from rolling to nvim-tree, could you please try the new changes and take it from there? you could now rely on lir.nvim without dealing with nvim-tree.

**Comment by martin-braun** [comment]
@kylo252 I'm a beginner with `nvim` and `lvim`. Can I use the rolling release with nvim 0.7.2? I want to keep the editor stable. Also has the rolling of Lunar lir.nvim built in, so I can switch to it easily when nvim-tree keeps making issues?

**Comment by martin-braun** [comment]
@kylo252 Thank you, I'm on the master branch now, but I can confirm once again, the issue remains.

**Comment by kylo252** [comment]
@martin-braun, you should be on _rolling_ branch to test the new configuration

**Comment by martin-braun** [comment]
@kylo252 Thank you. However, out of frustration with this I gave NvChad a try and I'm happy with it, so I gonna stick with that.

**Comment by kylo252** [comment]
@martin-braun, no worries! 

P.s. you can have lunarvim side-by-side with any other neovim configuration :)

**Comment by pavlosSkev** [comment]
Has anyone managed to solve this issue?
