### ISSUE TITLE
Fresh install throws NvimTree errors

### ISSUE THREAD

**Issue by Sigurs** [LunarVim/LunarVim#2528]
### Problem description

First time user. 

1. Followed installation instructions
2. Ran `lvim`
3. Getting errors? Check screenshots.

### LunarVim version

e81d24e

### Neovim version (>= 0.6.1)

NVIM v0.7.0 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include Compiled by runner@fv-az316-460  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: " /home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"  Run :checkhealth for more info

### Operating system/version

Ubuntu 22.04 LTS

### Relevant log output

```shell
null-ls: require("null-ls.health").check()
========================================================================
  - INFO: no sources registered

nvim: health#nvim#check
========================================================================
## Configuration
  - WARNING: Missing user config file: /home/XYZ/.config/nvim/init.vim
    - ADVICE:
      - :help |init.vim|

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='tmux'
  - INFO: $SSH_TTY='/dev/pts/0'

## tmux
  - ERROR: `escape-time` (500) is higher than 300ms
    - ADVICE:
      - set escape-time in ~/.tmux.conf:
          set-option -sg escape-time 10
      - https://github.com/neovim/neovim/wiki/FAQ
  - INFO: Checking stuff
  - WARNING: `focus-events` is not enabled. |'autoread'| may not work.
    - ADVICE:
      - (tmux 1.9+ only) Set `focus-events` in ~/.tmux.conf:
          set-option -g focus-events on
  - INFO: $TERM: screen
  - ERROR: $TERM should be "screen-256color" or "tmux-256color" in tmux. Colors might look wrong.
    - ADVICE:
      - Set default-terminal in ~/.tmux.conf:
          set-option -g default-terminal "screen-256color"
      - https://github.com/neovim/neovim/wiki/FAQ
  - WARNING: Neither Tc nor RGB capability set. True colors are disabled. |'termguicolors'| won't work properly.
    - ADVICE:
      - Put this in your ~/.tmux.conf and replace XXX by your $TERM outside of tmux:
          set-option -sa terminal-overrides ',XXX:RGB'
      - For older tmux versions use this instead:
          set-option -ga terminal-overrides ',XXX:Tc'

nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.6.0
  - WARNING: **Go**: not available
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - WARNING: **julia**: not available
  - OK: **sh**: `Ok`
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
  - OK: **tar**: `tar (GNU tar) 1.34`
  - OK: **gzip**: `gzip 1.10`
  - OK: **wget**: `GNU Wget 1.21.2 built on linux-gnu.`
  - OK: **python3**: `Python 3.10.4`
  - OK: **node**: `v18.0.0`
  - OK: **Ruby**: `ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]`
  - OK: **cargo**: `cargo 1.57.0`
  - OK: **curl**: `curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.11`
  - OK: **java**: `Ok`
  - OK: **RubyGem**: `3.3.5`
  - OK: **javac**: `Ok`
  - OK: **npm**: `8.6.0`
  - OK: **pip3**: `pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)`

nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.6 (ccd6bf554d922596ce905730d98a77af368bba5c) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v18.0.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - bash           ✓ ✓ ✓ . ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - css            ✓ . ✓ ✓ ✓ 
  - java           ✓ ✓ . ✓ ✓ 
  - tsx            ✓ ✓ ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/bin/python3
  - INFO: Other python executable: /bin/python3
  - INFO: Python version: 3.10.4
  - INFO: pynvim version: 0.4.2 (outdated; from /usr/lib/python3/dist-packages/neovim)
  - WARNING: Latest pynvim is NOT installed: 0.4.3

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.
      - You may disable this provider (and warning) by adding `let g:loaded_ruby_provider = 0` to your init.vim

## Node.js provider (optional)
  - INFO: Node.js: v18.0.0
  - INFO: Nvim node.js host: /home/XYZ/.nvm/versions/node/v18.0.0/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.10.1

## Perl provider (optional)
  - WARNING: "Neovim::Ext" cpan module is not installed
    - ADVICE:
      - See :help |provider-perl| for more information.
      - You may disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim

telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - ERROR: rg: not found. `live-grep` finder will not function without [BurntSushi/ripgrep](https://github.com/BurntSushi/ripgrep) installed.
  - WARNING: fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided

## Telescope Extension: `projects`
  - INFO: No healthcheck provided

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: /home/XYZ/.cache/lvim/lsp.log
  - INFO: Log size: 0 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 14
  - OK: Loaded parser for bash: ABI version 13
  - OK: Loaded parser for css: ABI version 13
  - OK: Loaded parser for java: ABI version 13
  - OK: Loaded parser for javascript: ABI version 13
  - OK: Loaded parser for json: ABI version 13
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for python: ABI version 13
  - OK: Loaded parser for rust: ABI version 13
  - OK: Loaded parser for tsx: ABI version 13
  - OK: Loaded parser for typescript: ABI version 13
  - OK: Loaded parser for yaml: ABI version 13
  - OK: Loaded parser for c: ABI version 13

which_key: health#which_key#check
========================================================================
## WhichKey: checking conflicting keymaps
  - WARNING: buffer-local keymap overriding global for mode **"n"**, buf: 0, lhs: **"<leader>sr"**
  - INFO: old rhs: `<CMD>Telescope oldfiles<CR>`
  - INFO: new rhs: `<cmd>Telescope oldfiles<cr>`
  - WARNING: buffer-local keymap overriding global for mode **"n"**, buf: 0, lhs: **"<leader>st"**
  - INFO: old rhs: `<CMD>Telescope live_grep<CR>`
  - INFO: new rhs: `<cmd>Telescope live_grep<cr>`
  - WARNING: buffer-local keymap overriding global for mode **"n"**, buf: 0, lhs: **"<leader>Lc"**
  - INFO: old rhs: `<CMD>edit /home/XYZ/.config/lvim/config.lua <CR>`
  - INFO: new rhs: `<cmd>edit /home/XYZ/.config/lvim/config.lua<cr>`
  - WARNING: buffer-local keymap overriding global for mode **"n"**, buf: 0, lhs: **"<leader>f"**
  - INFO: old rhs: `<CMD>Telescope find_files<CR>`
  - INFO: new rhs: `<cmd>lua require("which-key").execute(1)<cr>`
```

### Screenshots

![image](https://user-images.githubusercontent.com/10909187/165499844-25fb7f28-e276-4d5d-ad57-9b6e2daf6f3a.png)
![image](https://user-images.githubusercontent.com/10909187/165500785-534416a4-128c-4b9d-be58-7d2286924c01.png)

**Comment by n67094** [comment]
Same issue, I can tell that the probleme is between https://github.com/kyazdani42/nvim-tree.lua/blob/master/doc/nvim-tree-lua.txt and ~/.local/share/lunarvim/lvim/lua/lvim/core/nvimtree.lua (didn't try to fix it yet)

**Comment by abzcoding** [comment]
it was fixed in `rolling`, we probably need to merge rolling into master
cc: @kylo252

**Comment by kylo252** [comment]
> it was fixed in `rolling`, we probably need to merge rolling into master cc: @kylo252

I was basically waiting for #2526

**Comment by Sigurs** [comment]
Just tested rolling-3de829e
![image](https://user-images.githubusercontent.com/10909187/165586798-6076d28b-4f65-4bed-ae1d-cfc9ed2103eb.png)

**Comment by bobek** [comment]
> Edit: Not sure what did it, but on the machine I installed rolling-3de829e on it just stopped complaining.

I had the same issue, `:LvimSyncCorePlugins` did the trick for me.

**Comment by Sigurs** [comment]
> > Edit: Not sure what did it, but on the machine I installed rolling-3de829e on it just stopped complaining.
> 
> I had the same issue, `:LvimSyncCorePlugins` did the trick for me.

That was one of the commands I ran on `rolling-3de829e`, so probably that. 👍 
On `e81d24e` it did not fix the issue though.

**Comment by abzcoding** [comment]
@Sigurs the plugin version are locked in each `rolling` commit
for example 3de829e contains nvim-tree `"commit": "ce463a5"`
and e81d24e contains nvim-tree `"commit": "477536c"`

that is why

**Comment by abzcoding** [comment]
you can check out each plugin version here
https://github.com/LunarVim/LunarVim/blob/3de829e76ed3d90b25250b1ab76f6425146af9d2/snapshots/default.json#L68-L70

**Comment by jinlinux** [comment]
> @Sigurs the plugin version are locked in each commit for example [3de829e](https://github.com/LunarVim/LunarVim/commit/3de829e76ed3d90b25250b1ab76f6425146af9d2) contains nvim-tree `"commit": "ce463a5"` and [e81d24e](https://github.com/LunarVim/LunarVim/commit/e81d24e3c34cc9718b74de3c0f294c53fcbe82a8) contains nvim-tree `"commit": "477536c"`
> 
> that is why, running `:LvimSyncCorePlugins` makes sure your plugin version gets updated from `477536c` to `ce463a5` which would fix the issue

I managed to fix the NvimTree warning but now my terraform lsp stopped working(was working prior)
![image](https://user-images.githubusercontent.com/28153237/165684105-bf6c19ff-2f29-40f7-a469-f608e6f77497.png)
Any ideas?

**Comment by abzcoding** [comment]
> I managed to fix the NvimTree warning but now my terraform lsp stopped working(was working prior) ![image](https://user-images.githubusercontent.com/28153237/165684105-bf6c19ff-2f29-40f7-a469-f608e6f77497.png) Any ideas?

run `:LspInstallInfo`, make sure `terraform` is installed

**Comment by jinlinux** [comment]
> > I managed to fix the NvimTree warning but now my terraform lsp stopped working(was working prior) ![image](https://user-images.githubusercontent.com/28153237/165684105-bf6c19ff-2f29-40f7-a469-f608e6f77497.png) Any ideas?
> 
> run `:LspInstallInfo`, make sure `terraform` is installed

it was installed. Looks like `0eb85a7` fixed it though.
