### ISSUE TITLE
[Bug]: No Diagnostics on Ruby

### ISSUE THREAD

**Issue by jonathan-raines** [LunarVim/LunarVim#945]
### Problem description

- Using rbenv as Ruby version manager
- Using 2.7.1
- gem install solargraph, gem install rails
- LspInstall solargraph

I no longer have diagnostics on Ruby files. I have not modified any of the Ruby settings in default-config.lua. Also how could I switch back to using Rubocop? I have a rubocop.yml file that used to be sourced for linting and formatting and all of this has stopped working around the time Rufo was added as the Ruby formatter.

I am up to date with Neovim and I'm on the Rolling LunarVim release.

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/nvim/ftplugin/)
- [X] I checked the options (~/.config/nvim/lv-config.lua)
- [X] The programs specified by the config are installed

### LunarVim version

0.4.8

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+42-geece0735f

### Screenshots
![image](https://user-images.githubusercontent.com/5840124/125691332-b443cd7c-b9f1-4750-b218-218a1eb3fd75.png)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by abzcoding** [comment]
for changing the formatter, you can do this 
```lua
-- lv-config.lua
O.lang.ruby.formatter.exe = "robocop"
O.lang.ruby.formatter.args =  {}
```

**Comment by jonathan-raines** [comment]
Running rubocop in that fashion runs the linter and checks for errors. I used to receive diagnostics from the LSP depending on the `.rubocop.yml` file for the project. E.g. line too long. Format on save used to fix most, if not all of those errors for me. Now I don't receive any type of diagnostics from the LSP.

`:echom &filetype = ruby`

**Comment by abzcoding** [comment]
> Running rubocop in that fashion runs the linter and checks for errors. I used to receive diagnostics from the LSP depending on the `.rubocop.yml` file for the project. E.g. line too long. Format on save used to fix most, if not all of those errors for me. Now I don't receive any type of diagnostics from the LSP.
> 
> `:echom &filetype = ruby`

can you provide your `~/.cache/nvim/lsp.log` so i can dig deeper

**Comment by jonathan-raines** [comment]
[lsp.log](https://github.com/ChristianChiarulli/LunarVim/files/6824508/lsp.log)
``

**Comment by abzcoding** [comment]
@jonathan-raines  can you test this :pleading_face: 
```bash
cd /tmp
git clone https://github.com/sirmike/sample-ruby-project.git
cd sample-ruby-project
nvim lib/bar.rb
```
are you able to see this diagnostics?
![diag](https://user-images.githubusercontent.com/10992695/125822934-75dfbf52-7dbb-43fb-8d0a-3cf54b0a43bf.png)

**Comment by jonathan-raines** [comment]
I can see that diagnostic

**Comment by abzcoding** [comment]
good :sweat_smile: , i think i've found the root cause , gonna file a PR later on

**Comment by abzcoding** [comment]
@jonathan-raines can you install `robocop-railse` and `mini_portile2-2.5.1` in the same project that raised those erros? and test it again

- either the solargraph lsp has some issues 
- or we've configured it in a wrong way.

cause this is what your `lsp.log` shows:
![lsp](https://user-images.githubusercontent.com/10992695/125846252-8358d588-7d6d-4a76-8c3b-477c521e372d.png)

basically if the solargraph or rubocop cannot find a gem they crash and don't show diagnostics which is odd.
can you test this theory on your end?

- basically start a simple ruby project without any dependencies
- test if the diagnoistics show and work
- try adding new code and check it again
- add a dependency but don't install the required gems ( this should cause the diagnostics to not show up)
- install the gems in question and open neovim again (this should fix the issue and let you see the diagnostics again)

**Comment by jonathan-raines** [comment]
I created a new rails project and diagnostics work. I added `gem factory_bot` to the Gemfile and did not install the gem. I quit and restarted Neovim and diagnostics still work.

On the existing project where I am not receiving diagnostics, `rubocop-rails` is already added to the Gemfile and installed. I ran `gem install mini_portile2` and restarted Neovim and the diagnostics still do not work :/.

**Comment by abzcoding** [comment]
> Okay performing `gem install mini_portile2` seems to have fixed diagnostics. `rubocop rails` was already included in the Gemfile and installed. I am getting a `filetype unknown` error which is interesting.

that one is a known issue #822

**Comment by jonathan-raines** [comment]
I closed the terminal session, reopened, navigated to the project, and opened Neovim and diagnostics are not working again.
[lsp.log](https://github.com/ChristianChiarulli/LunarVim/files/6826188/lsp.log)

**Comment by Tastyep** [comment]
You log spams
`fatal: not a git repository`

https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/solargraph.lua#L18

The language server requires a `Gemfile` or a `.git`, can you check that again ?

**Comment by jonathan-raines** [comment]
This project has both a `Gemfile` and a `.git`.

**Comment by rebuilt** [comment]
Does your path include any directories with spaces?

**Comment by jonathan-raines** [comment]
No spaces. I use `-` instead of spaces `/home/username/projects/ruby-project-directory`

**Comment by jonathan-raines** [comment]
@rebuilt I just figured out that I lose diagnostics whenever there is a `.rubocop.yml` file in the project directory. This file is used to configure certain aspects of `rubocop`. If that file is present, diagnostics do not work. 

Also I've noticed that `rufo` is no longer auto formatting code on save. I noticed the issue just in the past couple of days

**Comment by rebuilt** [comment]
Can you add this to your config file please
```
lvim.lang.ruby.formatters = {
  {
    exe = "rufo",
    args = {},
  }
}
```

**Comment by abzcoding** [comment]
in the latest `rolling` branch we are using `null-ls` so you can either not config anything and use the Language Server for formatting/linting or if use what rebuilt said if you want  `rufo`

**Comment by jonathan-raines** [comment]
I would prefer to not use rufo. I use to just receive auto formatting on save through rubocop configuration, i.e. if the line was too long it would break the line up on save. But right now the only way I can get auto save in a ruby project is to use rufo for some reason.

Anything I can provide for diagnostics? I am up to date on the latest rolling release. At one time LunarVim did auto format on save based on rubocop configuration. I believe I lost that functionality around the time that neoformat was introduced

**Comment by abzcoding** [comment]
> I would prefer to not use rufo. I use to just receive auto formatting on save through rubocop configuration, i.e. if the line was too long it would break the line up on save. But right now the only way I can get auto save in a ruby project is to use rufo for some reason.
> 
> Anything I can provide for diagnostics? I am up to date on the latest rolling release. At one time LunarVim did auto format on save based on rubocop configuration. I believe I lost that functionality around the time that neoformat was introduced

just to be sure, you do have this in your config right?
```lua
lvim.format_on_save = true
```

**Comment by rebuilt** [comment]
@abzcoding   Lsp formatting was turned off entirely.

@jonathan-raines Can you try this and see if it works
```
lvim.lsp.on_init_callback = function()
    client.resolved_capabilities.document_formatting = true
end
```

I can't test this for reasons, but I think that should work.  Disable rufo if you enabled it

**Comment by abzcoding** [comment]
> ```lua
> lvim.lsp.on_init_callback = function()
>     client.resolved_capabilities.document_formatting = true
> end
> ```

can can this works
```lua
lvim.lsp.on_init_callback = function(client, _bufnr)
  client.resolved_capabilities.document_formatting = true
end
```

**Comment by jonathan-raines** [comment]
Without `.rubocop.yml`
![image](https://user-images.githubusercontent.com/5840124/128033884-2edcfbfc-e75a-4f6f-b71c-a58c4e57f8db.png)

With `.rubocop.yml` added
![image](https://user-images.githubusercontent.com/5840124/128034404-769c24dc-7f86-40f5-9d15-d211e87e89f7.png)

An empty `.rubocop.yml` still allows diagnostics, so maybe something in the config is messing with diagnostics unless an empty config file is ignored.

**Comment by jonathan-raines** [comment]
> @jonathan-raines
> can confirm adding this works
> 
> ```lua
> lvim.format_on_save = true
> lvim.lsp.on_init_callback = function(client, _bufnr)
>   client.resolved_capabilities.document_formatting = true
> end
> ```

I added this to `config.lua` and it does not seem to format on save. These settings are set in `config.lua` `lvim.format_on_save = true` `lvim.lint_on_save = true`

**Comment by jonathan-raines** [comment]
Okay having a `.rubocop.yml` config file completely borks diagnostics and formatting. I can confirm it works without the `.rubocop.yml` file

**Comment by abzcoding** [comment]
> Okay having a `.rubocop.yml` config file completely borks diagnostics and formatting. I can confirm it works without the `.rubocop.yml` file

can you check `~/.cache/nvim/lsp.log`
you might need to file this issue with [solargraph](https://github.com/castwide/solargraph)

**Comment by jonathan-raines** [comment]
[lsp.log](https://github.com/ChristianChiarulli/LunarVim/files/6925010/lsp.log)

**Comment by rebuilt** [comment]
If you've been updating with git pull, you might also need to `:PackerSync` to make sure all the plugins are installed correctly.  Also can you double check the syntax of your rubocop.yml  or try a different yml file to verify:   https://github.com/rubocop/rubocop/blob/master/config/default.yml

**Comment by abzcoding** [comment]
maybe this causes the issue :thinking: 
```
[ ERROR ] 2021-08-03T09:48:39-0500 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"/home/jraines/.local/share/nvim/lspinstall/ruby/solargraph/solargraph"	"stderr"	"fatal: not a git repository (or any parent up to mount point /)\nStopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).\n"
```

**Comment by abzcoding** [comment]
[solargraph LS](https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#solargraph) only works if you have these files on root of your project
```
root_dir = root_pattern("Gemfile", ".git")
```

**Comment by jonathan-raines** [comment]
The issue came from the `.rubocop.yml` file. I still don't know what was formatted incorrectly but commenting out everything and adding everything line by line and now it works with my rubocop config file. Something must not have been indented correctly and was silently crashing.

**Comment by rebuilt** [comment]
@jonathan-raines Do you have any interest in providing a ruby specific config for the documentation site?

**Comment by rebuilt** [comment]
Do you have rubocop-rspec and rubocop-rails in your Gemfile?  Have you `bundle install` ed them?  Are they available in your path?

**Comment by jonathan-raines** [comment]
rubocop-rspec and rubocop-rails are in my Gemfile and they have been `bundle install`'ed The tests runs when using the command `rubocop --require rubocop-rails` in the terminal so I know the config file is functioning properly. But those errors pop up in `lsp.log`

**Comment by jonathan-raines** [comment]
[lsp.log](https://github.com/ChristianChiarulli/LunarVim/files/6931692/lsp.log)

**Comment by rebuilt** [comment]
I think it's not finding a gitfile or Gemfile because solargraph is launching from:

```lua
DATA_PATH .. "/lspinstall/ruby/solargraph/solargraph",
```

And in that directory there is no Gemfile.   

Can you add this to your config file please and confirm in the error logs that you no longer see errors about not finding the root folder `"fatal: not a git repository (or any parent up to mount point /)\nStopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).\n`

```
local util = require("lspconfig/util")
lvim.lang.ruby.lsp.setup = {
    cmd = { "solargraph", "stdio" },
    filetypes = { "ruby" },
    init_options = {
      formatting = true
    },
    root_dir = util.root_pattern("Gemfile", ".git"),
    settings = {
      solargraph = {
        diagnostics = true
      }
    }
}

```

You should only see this in the logfile

```
[ START ] 2021-08-04T19:24:50+0200 ] LSP logging initiated
[ ERROR ] 2021-08-04T19:24:51+0200 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"solargraph"	"stderr"	"Solargraph is listening on stdio PID=580988\n"

```

**Comment by jonathan-raines** [comment]
That does resolve the issue. Now there's no errors when `require: rubocop-rails` and diagnostics work

**Comment by abzcoding** [comment]
@rebuilt can you do a PR to `default-config.lua` so we can fix this for everyone :pleading_face:

**Comment by rebuilt** [comment]
@abzcoding  Yes, but the problem is, `:LspInstall ruby` will not be the happy path any more.  Users will need to `gem install solargraph`.

**Comment by abzcoding** [comment]
> @abzcoding Yes, but the problem is, `:LspInstall ruby` will not be the happy path any more. Users will need to `gem install solargraph`.

this is our current config:
```lua
  ruby = {
    formatters = {
      {
        -- @usage can be rufo
        exe = "",
        args = {},
      },
    },
    linters = {},
    lsp = {
      provider = "solargraph",
      setup = {
        cmd = {
          DATA_PATH .. "/lspinstall/ruby/solargraph/solargraph",
          "stdio",
        },
        on_attach = common_on_attach,
        on_init = common_on_init,
        capabilities = common_capabilities,
      },
    },
  },

```
i think changing it to this should resolve it
```lua
  ruby = {
    formatters = {
      {
        -- @usage can be rufo
        exe = "",
        args = {},
      },
    },
    linters = {},
    lsp = {
      provider = "solargraph",
      setup = {
        cmd = {
          DATA_PATH .. "/lspinstall/ruby/solargraph/solargraph",
          "stdio",
        },
        on_attach = common_on_attach,
        on_init = common_on_init,
        capabilities = common_capabilities,
        filetypes = { "ruby" },
        init_options = {
          formatting = true
        },
        root_dir = util.root_pattern("Gemfile", ".git"),
       settings = {
         solargraph = {
           diagnostics = true
         }
       },
      },
    },
  },
```

**Comment by abzcoding** [comment]
@jonathan-raines  can you test changing your
`~/.local/share/lunarvim/lvim/lua/default-config.lua` line 912 to look like that and test if it works or not
remove the part that you added to your config.lua for now

**Comment by rebuilt** [comment]
I think that should work.  I tested and I don't get the `GIT_DISCOVERY_ACROSS_FILESYSTEM ` message

**Comment by jonathan-raines** [comment]
> @jonathan-raines can you test changing your
> `~/.local/share/lunarvim/lvim/lua/default-config.lua` line 912 to look like that and test if it works or not
> comment the part that you added to your `config.lua` for now

This brings back the same issue on my end. I have removed the `solargraph` gem from the project's `Gemfile` and the issue still persists. The only thing that resolves it is @rebuilt 's initial suggestion to add to `config.lua`

**Comment by rebuilt** [comment]
@abzcoding 
The path is important here.  Launching from ` DATA_PATH .. "/lspinstall/ruby/solargraph/solargraph",` is going to give you a different path than launching locally with just `solargraph`.  The two paths will result in different root_detection.  

This is a little like the local prettier vs global prettier problem.  

To guarantee that solargraph will work, it has to be installed locally.  Launching solargraph from a different directory just doesn't work for all cases.  I'm not sure how to resolve it except to document the behavior, and tell users not to `LspInstall ruby`.   `LspInstall` will work for basic cases but breaks 'silently' for more complex cases.  (the log file still reports errors)

**Comment by jonathan-raines** [comment]
So I need to LspUninstall ruby and install solargraph via the gem instead?

**Comment by abzcoding** [comment]
> @abzcoding
> The path is important here. Launching from ` DATA_PATH .. "/lspinstall/ruby/solargraph/solargraph",` is going to give you a different path than launching locally with just `solargraph`. The two paths will result in different root_detection.
> 
> This is a little like the local prettier vs global prettier problem.
> 
> To guarantee that solargraph will work, it has to be installed locally. Launching solargraph from a different directory just doesn't work for all cases. I'm not sure how to resolve it except to document the behavior, and tell users not to `LspInstall ruby`. `LspInstall` will work for basic cases but breaks 'silently' for more complex cases. (the log file still reports errors)

yeah you are right, we need to document it under ruby in [here](https://www.lunarvim.org/languages/) maybe

**Comment by sanevillain** [comment]
Are the linked pull requests supposed to fix the lspinstall issues ? Because currently I have the solargraph language server installed but it's not working at all

**Comment by jonathan-raines** [comment]
You have to install solargraph via gem and LspUninstall solargraph

**Comment by sanevillain** [comment]
Well, I tried that in a ruby repository but that way the server isn't working at all. I don't know if I'm doing something wrong or what but if all I have to do is install solargraph with gem install and uninstall the ruby lsp, it isn't really working for me

**Comment by websebdev** [comment]
@sanevillain  After running `LspUninstall ruby`, `gem install solargraph` and then adding the following to lvim's config, I finally got it working. Only installing the solargraph gem seems not enough.
```rb
local util = require("lspconfig/util")
lvim.lang.ruby.lsp.setup = {
    cmd = { "solargraph", "stdio" },
    filetypes = { "ruby" },
    init_options = {
      formatting = true
    },
    root_dir = util.root_pattern("Gemfile", ".git"),
    settings = {
      solargraph = {
        diagnostics = true
      }
    }
}

```

**Comment by sanevillain** [comment]
@websebdev  Weird. I tried what you've suggested and the language server isn't working for me. Have you changed anything else besides the lines that you've pasted here ?

**Comment by websebdev** [comment]
@sanevillain No, nothing else.

**Comment by rebuilt** [comment]
@sanevillain Do you have a Gemfile?  Is your project in a git repo?   Look through `~/.cache/nvim/lsp.log` for log error messages.  
Look at `:LspInfo` to see if it reports errors.  Print the output of `messages`

**Comment by rebuilt** [comment]
@sanevillain Do you have a Gemfile?  Is your project in a git repo?   Look through `~/.cache/nvim/lsp.log` for log error messages.  
Look at `:LspInfo` to see if it reports errors.  Print the output of `messages`

**Comment by sanevillain** [comment]
@rebuilt I updated lvim and it seems to be working now with  a Gemfile

**Comment by rebuilt** [comment]
`:LspInstall solargraph` works in the latest LunarVim.  Any version of LunarVim later than `d01ba08` should work.  You'll probably have to `gem uninstall solargraph`, then `:LspInstall solargraph` 

https://www.lunarvim.org/languages/ruby.html#install-syntax-highlighting

**Comment by Mate2xo** [comment]
The previous fix with the `lvim.lang` option, and the `LspUninstall solargraph`, with the solargraph gem locally installed worked for me. But now with the new update, LSP 'barerly' works, or just doesn't work in Ruby anymore. It seems that the LSP setup Lunarvim uses does not use the local environment properly.
E.g.:
- My global version of Ruby is 3.0
- In a project I work on, it's Ruby 2.5
- When I launch Lunarvim from the Ruby 2.5 folder, LSP crashes because it cannot find Bundler, although it is installed in both versions of Ruby. LSP uses rubygems specifications from Ruby 3.0 though, and check this GEM_PATH: `.local/share/nvim/lsp_servers/solargraph'`
- When I launch Lunarvim from another folder (let's say `/home`), and then I navigate to my Ruby 2.5 project, solargraph gets attached to the buffer, but `[WARN] Failed to load gems from bundle at /home/tim/Projects/CapSens/le-conservateur/Le-Conservateur-Back\n`. So it launches, but doesn't work anyway
- When I use a project in Ruby 2.7, launching Lunarvim from, or outside, the folder, the correct version of Ruby is used (2.7), but the gems loading from the local bundle still fails. BUT LSP 'works' and I get some visual diagnostic of my code. I cannot use the `solargraph-reek` though, because the LSP tells me that it 'does not exist' (but it exists and is installed in the 2.7)

So yeah I don't know if that helps, but I don't have any of these problems with [coc.nvim](https://github.com/neoclide/coc.nvim). I even tried the exact same setup through NlspConfig. Also tried this with a fresh install of Lunarvim. So maybe this could come either from NlspConfig, or LspInstaller? I don't know where to look to find a solution, any suggestion would be welcome.

**Comment by Mate2xo** [comment]
The previous fix with the `lvim.lang` option, and the `LspUninstall solargraph`, with the solargraph gem locally installed worked for me. But now with the new update, LSP 'barerly' works, or just doesn't work in Ruby anymore. It seems that the LSP setup Lunarvim uses does not use the local environment properly.
E.g.:
- My global version of Ruby is 3.0
- In a project I work on, it's Ruby 2.5
- When I launch Lunarvim from the Ruby 2.5 folder, LSP crashes because it cannot find Bundler, although it is installed in both versions of Ruby. LSP uses rubygems specifications from Ruby 3.0 though, and check this GEM_PATH: `.local/share/nvim/lsp_servers/solargraph'`
- When I launch Lunarvim from another folder (let's say `/home`), and then I navigate to my Ruby 2.5 project, solargraph gets attached to the buffer, but `[WARN] Failed to load gems from bundle at /the projet folder name/`. So it launches, but doesn't work anyway
- When I use a project in Ruby 2.7, launching Lunarvim from, or outside, the folder, the correct version of Ruby is used (2.7), but the gems loading from the local bundle still fails. BUT LSP 'works' and I get some visual diagnostic of my code. I cannot use the `solargraph-reek` though, because the LSP tells me that it 'does not exist' (but it exists and is installed in the 2.7)

So yeah I don't know if that helps, but I don't have any of these problems with [coc.nvim](https://github.com/neoclide/coc.nvim). I even tried the exact same setup through NlspConfig. Also tried this with a fresh install of Lunarvim. So maybe this could come either from NlspConfig, or LspInstaller? I don't know where to look to find a solution, any suggestion would be welcome.

**Comment by edward-mb** [comment]
I use _rbenv_ with _rubocop, standard, solargraph, and reek_ installed via `gem install` or _bundler_, with custom per-project configurations of `.solargraph.yml` and `.rubocop.yml` that include plugins such as `solargraph-reek`

I recently updated via `lvim +LvimUpdate +q` and `:PackerSync` and solargraph diagnostics and formatting stoped working, there are no errors in `lsp.logs`

Lsp completion works but not the diagnostics

***While writing this I found out that***
 `require("lvim.lsp.manager").setup("solargraph", opts)` ignores the overrided configuration
and instead using `require("lspconfig")["solargraph"].setup(opts)` works

### Solargraph override
```lua
vim.list_extend(lvim.lsp.override, { "solargraph" })

local util = require("lspconfig/util")
local opts = {
    cmd = { "solargraph", "stdio" },
    filetypes = { "ruby" },
    init_options = {
      formatting = true
    },
    root_dir = util.root_pattern("Gemfile", ".git"),
    settings = {
      solargraph = {
        diagnostics = true
      }
    }
}
 # require("lvim.lsp.manager").setup("solargraph", opts)
 require("lspconfig")["solargraph"].setup(opts)
```
### .solargraph.yml
```yml
include:
  - "**/*.rb"
exclude:
  - spec/**/*
  - test/**/*
  - vendor/**/*
  - ".bundle/**/*"
require: []
domains: []
reporters:
  - rubocop
  - require_not_found
  - reek

formatter:
  rubocop:
    cops: safe
    except: []
    only: []
    extra_args: []
require_paths: []
plugins:
  - solargraph-reek

max_files: 5000
```
### .rubocop.yml
```yml
inherit_mode:
  merge:
    - Exclude

inherit_gem:
  standard: config/base.yml

require:
  - rubocop-performance
  - standard/cop/block_single_line_braces
  # - rubocop-rails
  - rubocop-rspec
  # - rubocop-minitest
  # - rubocop-rake

Lint/DuplicateMethods:
  Enabled: false

AllCops:
  NewCops: enable
```

**Comment by duduribeiro** [comment]
👋 

hey folks. I'm having this issue with lunarvim 

someinfo:

```
                                      Buffer info
                                      * filetype:                ruby
                                      * bufnr:                   17
                                      * treesitter status:       active
                                      
                                      Active client(s)
                                      * name:                      solargraph
                                      * id:                        1
                                      * supported filetype(s):     ruby
                                      * attached buffers:          17
                                      * root_dir pattern:          17
                                      * capabilities:              find_references | document_highlight  | text_document_save
                                                                   document_symbol | rename              | completion
                                                                   hover           | document_formatting | text_document_open_close
                                                                   goto_definition | workspace_symbol    | signature_help
                                      
                                      Overridden ruby server(s)
                                      * list: sorbet
                                      
                                      Formatters info
                                      * Active: 
                                      * Supported: [rubocop, rufo, standardrb]
                                      
                                      Linters info
                                      * Active: 
                                      * Supported: [rubocop, standardrb]
                                      
                                      Code actions info
                                      * Active: 
```

lunarvim version: "c8157a0"


and it is not reporting back the diagnostics

![image](https://user-images.githubusercontent.com/771411/154353791-7e0273b0-c418-4569-9f79-d57627dd3bc0.png)

it is weird for me because looks like LSP is working
![image](https://user-images.githubusercontent.com/771411/154354345-df9f1f84-7fbc-4836-9a8c-07aef9a79bdd.png)



see that it is not reporting that this line is wrong 🤔 

this is my

<details>
<summary>lsp.log</summary>
[START][2022-02-16 17:38:59] LSP logging initiated
[ERROR][2022-02-16 17:39:23] .../vim/lsp/rpc.lua:420	"rpc"	"solargraph"	"stderr"	"Solargraph is listening on stdio PID=40396\n"
[ERROR][2022-02-16 17:39:24] .../vim/lsp/rpc.lua:420	"rpc"	"solargraph"	"stderr"	"[WARN] /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/source/git.rb:214:in `rescue in load_spec_files': https://github.com/rails/rails.git (at 7-0-stable@846031a) is not yet checked out. Run `bundle install` first. (Bundler::GitError)\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/source/git.rb:210:in `load_spec_files'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/source/path.rb:107:in `local_specs'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/source/git.rb:178:in `specs'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/lazy_specification.rb:88:in `__materialize__'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/spec_set.rb:75:in `block in materialize'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/spec_set.rb:72:in `map!'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/spec_set.rb:72:in `materialize'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/definition.rb:468:in `materialize'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/definition.rb:240:in `specs_for'\n\tfrom -e:1:in `block in <main>'\n\tfrom -e:1:in `chdir'\n\tfrom -e:1:in `<main>'\n/Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/source/path.rb:209:in `load_spec_files': The path `/Users/cadu/.local/share/nvim/lsp_servers/solargraph/bundler/gems/rails-846031abe166` does not exist. (Bundler::PathError)\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/source/git.rb:211:in `load_spec_files'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/source/path.rb:107:in `local_specs'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/source/git.rb:178:in `specs'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/lazy_specification.rb:88:in `__materialize__'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/spec_set.rb:75:in `block in materialize'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/spec_set.rb:72:in `map!'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/spec_set.rb:72:in `materialize'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/definition.rb:468:in `materialize'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/definition.rb:240:in `specs_for'\n\tfrom -e:1:in `block in <main>'\n\tfrom -e:1:in `chdir'\n\tfrom -e:1:in `<main>'\n\n"
[ERROR][2022-02-16 17:39:24] .../vim/lsp/rpc.lua:420	"rpc"	"solargraph"	"stderr"	"[WARN] Failed to load gems from bundle at /Users/cadu/code/jyn\n"
[ERROR][2022-02-16 17:39:26] .../vim/lsp/rpc.lua:420	"rpc"	"solargraph"	"stderr"	"#<Thread:0x0000000104378908 /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/solargraph-0.44.3/lib/solargraph/language_server/host/diagnoser.rb:45 run> terminated with exception (report_on_exception is true):\n"
[ERROR][2022-02-16 17:39:26] .../vim/lsp/rpc.lua:420	"rpc"	"solargraph"	"stderr"	"<internal:/Users/cadu/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- standard (LoadError)\n"
[ERROR][2022-02-16 17:39:26] .../vim/lsp/rpc.lua:420	"rpc"	"solargraph"	"stderr"	"\tfrom <internal:/Users/cadu/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/rubocop-1.25.1/lib/rubocop/config_loader_resolver.rb:17:in `block (2 levels) in resolve_requires'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/rubocop-1.25.1/lib/rubocop/config_loader_resolver.rb:13:in `each'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/rubocop-1.25.1/lib/rubocop/config_loader_resolver.rb:13:in `block in resolve_requires'\n\tfrom <internal:kernel>:90:in `tap'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/rubocop-1.25.1/lib/rubocop/config_loader_resolver.rb:12:in `resolve_requires'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/rubocop-1.25.1/lib/rubocop/config_loader.rb:44:in `load_file'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/rubocop-1.25.1/lib/rubocop/config_loader.rb:103:in `configuration_from_file'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/rubocop-1.25.1/lib/rubocop/config_store.rb:68:in `for_dir'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/rubocop-1.25.1/lib/rubocop/config_store.rb:58:in `for'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/rubocop-1.25.1/lib/rubocop/target_finder.rb:190:in `block in process_explicit_path'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/rubocop-1.25.1/lib/rubocop/target_finder.rb:189:in `reject'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/rubocop-1.25.1/lib/rubocop/target_finder.rb:189:in `process_explicit_path'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/rubocop-1.25.1/lib/rubocop/target_finder.rb:40:in `block in find'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/rubocop-1.25.1/lib/rubocop/target_finder.rb:36:in `each'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/rubocop-1.25.1/lib/rubocop/target_finder.rb:36:in `find'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/rubocop-1.25.1/lib/rubocop/runner.rb:77:in `find_target_files'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/rubocop-1.25.1/lib/rubocop/runner.rb:42:in `run'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/solargraph-0.44.3/lib/solargraph/diagnostics/rubocop.rb:29:in `block in diagnose'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/solargraph-0.44.3/lib/solargraph/diagnostics/rubocop_helpers.rb:57:in `redirect_stdout'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/solargraph-0.44.3/lib/solargraph/diagnostics/rubocop.rb:29:in `diagnose'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/solargraph-0.44.3/lib/solargraph/library.rb:363:in `block in diagnose'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/solargraph-0.44.3/lib/solargraph/library.rb:362:in `each_pair'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/solargraph-0.44.3/lib/solargraph/library.rb:362:in `diagnose'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/solargraph-0.44.3/lib/solargraph/language_server/host.rb:211:in `diagnose'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/solargraph-0.44.3/lib/solargraph/language_server/host/diagnoser.rb:66:in `tick'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/solargraph-0.44.3/lib/solargraph/language_server/host/diagnoser.rb:47:in `block in start'\n"
</details>

I see some stuffs on log like:

[ERROR][2022-02-16 17:39:24] .../vim/lsp/rpc.lua:420	"rpc"	"solargraph"	"stderr"	"[WARN] Failed to load gems from bundle at /Users/cadu/code/jyn\n"

[ERROR][2022-02-16 17:39:26] .../vim/lsp/rpc.lua:420	"rpc"	"solargraph"	"stderr"	"#<Thread:0x0000000104378908 /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/solargraph-0.44.3/lib/solargraph/language_server/host/diagnoser.rb:45 run> terminated with exception (report_on_exception is true):\n"
[ERROR][2022-02-16 17:39:26] .../vim/lsp/rpc.lua:420	"rpc"	"solargraph"	"stderr"	"<internal:/Users/cadu/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- standard (LoadError)\n"

and
[ERROR][2022-02-16 17:39:24] .../vim/lsp/rpc.lua:420	"rpc"	"solargraph"	"stderr"	"[WARN] /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/source/git.rb:214:in `rescue in load_spec_files': https://github.com/rails/rails.git (at 7-0-stable@846031a) is not yet checked out. Run `bundle install` first. (Bundler::GitError)\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/source/git.rb:210:in `load_spec_files'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/source/path.rb:107:in `local_specs'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/source/git.rb:178:in `specs'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/lazy_specification.rb:88:in `__materialize__'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/spec_set.rb:75:in `block in materialize'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/spec_set.rb:72:in `map!'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/spec_set.rb:72:in `materialize'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/definition.rb:468:in `materialize'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/definition.rb:240:in `specs_for'\n\tfrom -e:1:in `block in <main>'\n\tfrom -e:1:in `chdir'\n\tfrom -e:1:in `<main>'\n/Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/source/path.rb:209:in `load_spec_files': The path `/Users/cadu/.local/share/nvim/lsp_servers/solargraph/bundler/gems/rails-846031abe166` does not exist. (Bundler::PathError)\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/source/git.rb:211:in `load_spec_files'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/source/path.rb:107:in `local_specs'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/source/git.rb:178:in `specs'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/lazy_specification.rb:88:in `__materialize__'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/spec_set.rb:75:in `block in materialize'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/spec_set.rb:72:in `map!'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/spec_set.rb:72:in `materialize'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/definition.rb:468:in `materialize'\n\tfrom /Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/lib/bundler/de


any tips on how can I get it working??

**Comment by rebuilt** [comment]
@duduribeiro 
Do you have rubocop installed?

**Comment by duduribeiro** [comment]
@rebuilt I have on my Gemfile and also on the global list


```
cadu@mbpro-cadu ~/c/jyn (main)> which ruby
/Users/cadu/.asdf/shims/ruby
cadu@mbpro-cadu ~/c/jyn (main)> ruby -v
ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x86_64-darwin21]
cadu@mbpro-cadu ~/c/jyn (main)> gem list | grep rubocop
rubocop (1.25.1, 1.25.0, 1.24.1, 0.52.0)
rubocop-ast (1.15.1)
rubocop-minitest (0.17.1, 0.17.0)
rubocop-packaging (0.5.1)
rubocop-performance (1.13.2, 1.13.1)
rubocop-rails (2.13.2)
```

**Comment by duduribeiro** [comment]
I also have standard

```
cadu@mbpro-cadu ~/c/jyn (main)> gem list | grep standard
standard (1.7.2, 1.7.0, 1.6.0)
standardrb (1.0.0)
```

because I use it on my .rubocop.yml

```
require:
  - standard
  - rubocop-minitest

inherit_gem:
  standard: config/base.yml

AllCops:
  Exclude:
    - "vendor/**/*"
    - "tmp/**/*"
    - "bin/**/*"
    - "db/**/*"
    - "node_modules/**/*"
    - "storage/**/*"

Minitest:
  Enabled: true

```

**Comment by rebuilt** [comment]
@duduribeiro 
Your error logs say some gems aren't found and that you should 'Run bundle install first. '

**Comment by duduribeiro** [comment]
@rebuilt yeah, I have run bundle.

the project is running. 


```
cadu@mbpro-cadu ~/c/jyn (main)> bin/dev
system | Tmux socket name: overmind-jyn-xHMcVq0Fo9e6Xw9sGJ-iVN
system | Tmux session ID: jyn
system | Listening at ./.overmind.sock
js     | Started with pid 41601...
css    | Started with pid 41602...
web    | Started with pid 41600...
yarn run v1.22.17
$ tailwindcss -i ./app/assets/stylesheets/application.tailwind.css -o ./app/assets/builds/application.css --watch
yarn run v1.22.17
$ esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds --watch
js     | [watch] build finished, watching for changes...
css    |
css    | Rebuilding...
css    | Done in 411ms.
web    | => Booting Puma
web    | => Rails 7.0.1 application starting in development
web    | => Run `bin/rails server --help` for more startup options
web    | Puma starting in single mode...
web    | * Puma version: 5.6.1 (ruby 3.1.0-p0) ("Birdie's Version")
web    | *  Min threads: 5
web    | *  Max threads: 5
web    | *  Environment: development
web    | *          PID: 41739
web    | * Listening on http://0.0.0.0:3000
web    | Use Ctrl-C to stop
web    | Started GET "/" for 127.0.0.1 at 2022-02-16 18:35:31 -0300
web    |   ActiveRecord::SchemaMigration Pluck (2.0ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
web    | Processing by HomeController#index as HTML
web    |   Rendering layout layouts/site.html.erb
web    |   Rendering home/index.html.erb within layouts/site
web    |   Rendered shared/_flash.html.erb (Duration: 0.5ms | Allocations: 395)
web    |   Rendered home/index.html.erb within layouts/site (Duration: 28.7ms | Allocations: 24115)
web    |   Rendered layout layouts/site.html.erb (Duration: 37.5ms | Allocations: 24900)
web    | Completed 200 OK in 215ms (Views: 49.2ms | ActiveRecord: 0.0ms | Allocations: 32341)
web    |
web    |
web    | Started GET "/assets/application-2cffa876a68ca31ce1b8ecbbe02efb058626b040.css" for 127.0.0.1 at 2022-02-16 18:35:32 -0300
web    | Started GET "/assets/application-7e349d778e40ad9c69d775b17a63340557381ba6.js" for 127.0.0.1 at 2022-02-16 18:35:32 -0300
web    | Started GET "/assets/chat-hero-296524c15c559187357278be4733d385285f88e1.svg" for 127.0.0.1 at 2022-02-16 18:35:32 -0300
```

I'm thinking that maybe `lsp` is using a different ruby version, maybe? 🤔

**Comment by duduribeiro** [comment]
I also saw this:

```
cadu@mbpro-cadu ~/c/jyn (main)> bundle -v
Bundler version 2.3.6
```

but on LSP logs I see it is using a bundler inside solargraph with a different version

```
/Users/cadu/.local/share/nvim/lsp_servers/solargraph/gems/bundler-2.3.7/
```

**Comment by duduribeiro** [comment]
@rebuilt ok,

I've only added this 
```lua
require('lspconfig').solargraph.setup {
  cmd = { "solargraph", "stdio" }
}
```

to my config and it worked. why it don't work without? no idea 😂 


![image](https://user-images.githubusercontent.com/771411/154366924-b91ee8d7-5d24-4852-9898-2b856b15c4bd.png)

thanks

**Comment by Juraci** [comment]
@duduribeiro  @dukex  where did you add this snippet? I'm getting the same behavior here, solargraph seems to be setup correctly but I get no diagnostics.

**Comment by duduribeiro** [comment]
> @duduribeiro @dukex where did you add this snippet? I'm getting the same behavior here, solargraph seems to be setup correctly but I get no diagnostics.

hey @Juraci. I added that snippet on my `~/.config/lvim/config.lua` file

**Comment by Juraci** [comment]
@duduribeiro thank you, although this snipped wasn't really necessary in my case, I opened a small ruby project and it all seemed to work just fine even without the snippet you provided, just by installing with `:LspInstall ruby`. 

I think my issue with the diagnostics happens only in this particular large rails project because it's dockerized (maybe?), meaning that everything runs with docker-compose, the gems are stored in a shared docker volume instead of locally. I will collect some more information and probably open another issue.
